// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router_grpc.proto

package com.vearch.grpc.entity;

/**
 * Protobuf type {@code AddRequest}
 */
public final class AddRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AddRequest)
    AddRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddRequest.newBuilder() to construct.
  private AddRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddRequest() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new AddRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            RequestHead.Builder subBuilder = null;
            if (head_ != null) {
              subBuilder = head_.toBuilder();
            }
            head_ = input.readMessage(RequestHead.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(head_);
              head_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            Document.Builder subBuilder = null;
            if (doc_ != null) {
              subBuilder = doc_.toBuilder();
            }
            doc_ = input.readMessage(Document.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(doc_);
              doc_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RouterGrpc.internal_static_AddRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RouterGrpc.internal_static_AddRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AddRequest.class, AddRequest.Builder.class);
  }

  public static final int HEAD_FIELD_NUMBER = 1;
  private RequestHead head_;
  /**
   * <code>.RequestHead head = 1;</code>
   * @return Whether the head field is set.
   */
  @Override
  public boolean hasHead() {
    return head_ != null;
  }
  /**
   * <code>.RequestHead head = 1;</code>
   * @return The head.
   */
  @Override
  public RequestHead getHead() {
    return head_ == null ? RequestHead.getDefaultInstance() : head_;
  }
  /**
   * <code>.RequestHead head = 1;</code>
   */
  @Override
  public RequestHeadOrBuilder getHeadOrBuilder() {
    return getHead();
  }

  public static final int DOC_FIELD_NUMBER = 4;
  private Document doc_;
  /**
   * <code>.Document doc = 4;</code>
   * @return Whether the doc field is set.
   */
  @Override
  public boolean hasDoc() {
    return doc_ != null;
  }
  /**
   * <code>.Document doc = 4;</code>
   * @return The doc.
   */
  @Override
  public Document getDoc() {
    return doc_ == null ? Document.getDefaultInstance() : doc_;
  }
  /**
   * <code>.Document doc = 4;</code>
   */
  @Override
  public DocumentOrBuilder getDocOrBuilder() {
    return getDoc();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (head_ != null) {
      output.writeMessage(1, getHead());
    }
    if (doc_ != null) {
      output.writeMessage(4, getDoc());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (head_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHead());
    }
    if (doc_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDoc());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AddRequest)) {
      return super.equals(obj);
    }
    AddRequest other = (AddRequest) obj;

    if (hasHead() != other.hasHead()) return false;
    if (hasHead()) {
      if (!getHead()
          .equals(other.getHead())) return false;
    }
    if (hasDoc() != other.hasDoc()) return false;
    if (hasDoc()) {
      if (!getDoc()
          .equals(other.getDoc())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHead()) {
      hash = (37 * hash) + HEAD_FIELD_NUMBER;
      hash = (53 * hash) + getHead().hashCode();
    }
    if (hasDoc()) {
      hash = (37 * hash) + DOC_FIELD_NUMBER;
      hash = (53 * hash) + getDoc().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AddRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AddRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AddRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AddRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AddRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AddRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AddRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AddRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AddRequest)
      AddRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RouterGrpc.internal_static_AddRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RouterGrpc.internal_static_AddRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddRequest.class, AddRequest.Builder.class);
    }

    // Construct using com.vearch.grpc.entity.AddRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (headBuilder_ == null) {
        head_ = null;
      } else {
        head_ = null;
        headBuilder_ = null;
      }
      if (docBuilder_ == null) {
        doc_ = null;
      } else {
        doc_ = null;
        docBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RouterGrpc.internal_static_AddRequest_descriptor;
    }

    @Override
    public AddRequest getDefaultInstanceForType() {
      return AddRequest.getDefaultInstance();
    }

    @Override
    public AddRequest build() {
      AddRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public AddRequest buildPartial() {
      AddRequest result = new AddRequest(this);
      if (headBuilder_ == null) {
        result.head_ = head_;
      } else {
        result.head_ = headBuilder_.build();
      }
      if (docBuilder_ == null) {
        result.doc_ = doc_;
      } else {
        result.doc_ = docBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AddRequest) {
        return mergeFrom((AddRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AddRequest other) {
      if (other == AddRequest.getDefaultInstance()) return this;
      if (other.hasHead()) {
        mergeHead(other.getHead());
      }
      if (other.hasDoc()) {
        mergeDoc(other.getDoc());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AddRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AddRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private RequestHead head_;
    private com.google.protobuf.SingleFieldBuilderV3<
        RequestHead, RequestHead.Builder, RequestHeadOrBuilder> headBuilder_;
    /**
     * <code>.RequestHead head = 1;</code>
     * @return Whether the head field is set.
     */
    public boolean hasHead() {
      return headBuilder_ != null || head_ != null;
    }
    /**
     * <code>.RequestHead head = 1;</code>
     * @return The head.
     */
    public RequestHead getHead() {
      if (headBuilder_ == null) {
        return head_ == null ? RequestHead.getDefaultInstance() : head_;
      } else {
        return headBuilder_.getMessage();
      }
    }
    /**
     * <code>.RequestHead head = 1;</code>
     */
    public Builder setHead(RequestHead value) {
      if (headBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        head_ = value;
        onChanged();
      } else {
        headBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.RequestHead head = 1;</code>
     */
    public Builder setHead(
        RequestHead.Builder builderForValue) {
      if (headBuilder_ == null) {
        head_ = builderForValue.build();
        onChanged();
      } else {
        headBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.RequestHead head = 1;</code>
     */
    public Builder mergeHead(RequestHead value) {
      if (headBuilder_ == null) {
        if (head_ != null) {
          head_ =
            RequestHead.newBuilder(head_).mergeFrom(value).buildPartial();
        } else {
          head_ = value;
        }
        onChanged();
      } else {
        headBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.RequestHead head = 1;</code>
     */
    public Builder clearHead() {
      if (headBuilder_ == null) {
        head_ = null;
        onChanged();
      } else {
        head_ = null;
        headBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.RequestHead head = 1;</code>
     */
    public RequestHead.Builder getHeadBuilder() {

      onChanged();
      return getHeadFieldBuilder().getBuilder();
    }
    /**
     * <code>.RequestHead head = 1;</code>
     */
    public RequestHeadOrBuilder getHeadOrBuilder() {
      if (headBuilder_ != null) {
        return headBuilder_.getMessageOrBuilder();
      } else {
        return head_ == null ?
            RequestHead.getDefaultInstance() : head_;
      }
    }
    /**
     * <code>.RequestHead head = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        RequestHead, RequestHead.Builder, RequestHeadOrBuilder>
        getHeadFieldBuilder() {
      if (headBuilder_ == null) {
        headBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            RequestHead, RequestHead.Builder, RequestHeadOrBuilder>(
                getHead(),
                getParentForChildren(),
                isClean());
        head_ = null;
      }
      return headBuilder_;
    }

    private Document doc_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Document, Document.Builder, DocumentOrBuilder> docBuilder_;
    /**
     * <code>.Document doc = 4;</code>
     * @return Whether the doc field is set.
     */
    public boolean hasDoc() {
      return docBuilder_ != null || doc_ != null;
    }
    /**
     * <code>.Document doc = 4;</code>
     * @return The doc.
     */
    public Document getDoc() {
      if (docBuilder_ == null) {
        return doc_ == null ? Document.getDefaultInstance() : doc_;
      } else {
        return docBuilder_.getMessage();
      }
    }
    /**
     * <code>.Document doc = 4;</code>
     */
    public Builder setDoc(Document value) {
      if (docBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        doc_ = value;
        onChanged();
      } else {
        docBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Document doc = 4;</code>
     */
    public Builder setDoc(
        Document.Builder builderForValue) {
      if (docBuilder_ == null) {
        doc_ = builderForValue.build();
        onChanged();
      } else {
        docBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Document doc = 4;</code>
     */
    public Builder mergeDoc(Document value) {
      if (docBuilder_ == null) {
        if (doc_ != null) {
          doc_ =
            Document.newBuilder(doc_).mergeFrom(value).buildPartial();
        } else {
          doc_ = value;
        }
        onChanged();
      } else {
        docBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Document doc = 4;</code>
     */
    public Builder clearDoc() {
      if (docBuilder_ == null) {
        doc_ = null;
        onChanged();
      } else {
        doc_ = null;
        docBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Document doc = 4;</code>
     */
    public Document.Builder getDocBuilder() {

      onChanged();
      return getDocFieldBuilder().getBuilder();
    }
    /**
     * <code>.Document doc = 4;</code>
     */
    public DocumentOrBuilder getDocOrBuilder() {
      if (docBuilder_ != null) {
        return docBuilder_.getMessageOrBuilder();
      } else {
        return doc_ == null ?
            Document.getDefaultInstance() : doc_;
      }
    }
    /**
     * <code>.Document doc = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Document, Document.Builder, DocumentOrBuilder>
        getDocFieldBuilder() {
      if (docBuilder_ == null) {
        docBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Document, Document.Builder, DocumentOrBuilder>(
                getDoc(),
                getParentForChildren(),
                isClean());
        doc_ = null;
      }
      return docBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AddRequest)
  }

  // @@protoc_insertion_point(class_scope:AddRequest)
  private static final AddRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AddRequest();
  }

  public static AddRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddRequest>() {
    @Override
    public AddRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AddRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public AddRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

