// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router_grpc.proto

package com.vearch.grpc.entity;

public interface DelByQueryeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DelByQueryeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ResponseHead head = 1;</code>
   * @return Whether the head field is set.
   */
  boolean hasHead();
  /**
   * <code>.ResponseHead head = 1;</code>
   * @return The head.
   */
  ResponseHead getHead();
  /**
   * <code>.ResponseHead head = 1;</code>
   */
  ResponseHeadOrBuilder getHeadOrBuilder();

  /**
   * <code>int32 DelNum = 2;</code>
   * @return The delNum.
   */
  int getDelNum();
}
