// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_model.proto

package com.vearch.grpc.entity;

/**
 * Protobuf enum {@code FieldType}
 */
public enum FieldType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>INT = 0;</code>
   */
  INT(0),
  /**
   * <code>LONG = 1;</code>
   */
  LONG(1),
  /**
   * <code>FLOAT = 2;</code>
   */
  FLOAT(2),
  /**
   * <code>DOUBLE = 3;</code>
   */
  DOUBLE(3),
  /**
   * <code>STRING = 4;</code>
   */
  STRING(4),
  /**
   * <code>VECTOR = 5;</code>
   */
  VECTOR(5),
  /**
   * <code>BOOL = 6;</code>
   */
  BOOL(6),
  /**
   * <code>GEOPOINT = 7;</code>
   */
  GEOPOINT(7),
  /**
   * <code>DATE = 8;</code>
   */
  DATE(8),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>INT = 0;</code>
   */
  public static final int INT_VALUE = 0;
  /**
   * <code>LONG = 1;</code>
   */
  public static final int LONG_VALUE = 1;
  /**
   * <code>FLOAT = 2;</code>
   */
  public static final int FLOAT_VALUE = 2;
  /**
   * <code>DOUBLE = 3;</code>
   */
  public static final int DOUBLE_VALUE = 3;
  /**
   * <code>STRING = 4;</code>
   */
  public static final int STRING_VALUE = 4;
  /**
   * <code>VECTOR = 5;</code>
   */
  public static final int VECTOR_VALUE = 5;
  /**
   * <code>BOOL = 6;</code>
   */
  public static final int BOOL_VALUE = 6;
  /**
   * <code>GEOPOINT = 7;</code>
   */
  public static final int GEOPOINT_VALUE = 7;
  /**
   * <code>DATE = 8;</code>
   */
  public static final int DATE_VALUE = 8;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static FieldType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static FieldType forNumber(int value) {
    switch (value) {
      case 0: return INT;
      case 1: return LONG;
      case 2: return FLOAT;
      case 3: return DOUBLE;
      case 4: return STRING;
      case 5: return VECTOR;
      case 6: return BOOL;
      case 7: return GEOPOINT;
      case 8: return DATE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<FieldType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      FieldType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<FieldType>() {
          public FieldType findValueByNumber(int number) {
            return FieldType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return DataModel.getDescriptor().getEnumTypes().get(0);
  }

  private static final FieldType[] VALUES = values();

  public static FieldType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private FieldType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:FieldType)
}

