// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_model.proto

package com.vearch.grpc.entity;

/**
 * <pre>
 * Whether index this field
 * </pre>
 *
 * Protobuf enum {@code FieldOption}
 */
public enum FieldOption
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Null = 0;</code>
   */
  Null(0),
  /**
   * <code>Index = 1;</code>
   */
  Index(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Null = 0;</code>
   */
  public static final int Null_VALUE = 0;
  /**
   * <code>Index = 1;</code>
   */
  public static final int Index_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static FieldOption valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static FieldOption forNumber(int value) {
    switch (value) {
      case 0: return Null;
      case 1: return Index;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<FieldOption>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      FieldOption> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<FieldOption>() {
          public FieldOption findValueByNumber(int number) {
            return FieldOption.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return DataModel.getDescriptor().getEnumTypes().get(1);
  }

  private static final FieldOption[] VALUES = values();

  public static FieldOption valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private FieldOption(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:FieldOption)
}

