// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router_grpc.proto

package com.vearch.grpc.entity;

public interface ForceMergeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ForceMergeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ResponseHead head = 1;</code>
   * @return Whether the head field is set.
   */
  boolean hasHead();
  /**
   * <code>.ResponseHead head = 1;</code>
   * @return The head.
   */
  ResponseHead getHead();
  /**
   * <code>.ResponseHead head = 1;</code>
   */
  ResponseHeadOrBuilder getHeadOrBuilder();

  /**
   * <code>.SearchStatus shards = 2;</code>
   * @return Whether the shards field is set.
   */
  boolean hasShards();
  /**
   * <code>.SearchStatus shards = 2;</code>
   * @return The shards.
   */
  SearchStatus getShards();
  /**
   * <code>.SearchStatus shards = 2;</code>
   */
  SearchStatusOrBuilder getShardsOrBuilder();
}
