// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_model.proto

package com.vearch.grpc.entity;

/**
 * Protobuf type {@code Item}
 */
public final class Item extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Item)
    ItemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Item.newBuilder() to construct.
  private Item(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Item() {
    msg_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Item();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Item(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            Error.Builder subBuilder = null;
            if (err_ != null) {
              subBuilder = err_.toBuilder();
            }
            err_ = input.readMessage(Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(err_);
              err_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            Document.Builder subBuilder = null;
            if (doc_ != null) {
              subBuilder = doc_.toBuilder();
            }
            doc_ = input.readMessage(Document.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(doc_);
              doc_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            msg_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DataModel.internal_static_Item_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DataModel.internal_static_Item_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Item.class, Item.Builder.class);
  }

  public static final int ERR_FIELD_NUMBER = 1;
  private Error err_;
  /**
   * <code>.Error err = 1;</code>
   * @return Whether the err field is set.
   */
  @Override
  public boolean hasErr() {
    return err_ != null;
  }
  /**
   * <code>.Error err = 1;</code>
   * @return The err.
   */
  @Override
  public Error getErr() {
    return err_ == null ? Error.getDefaultInstance() : err_;
  }
  /**
   * <code>.Error err = 1;</code>
   */
  @Override
  public ErrorOrBuilder getErrOrBuilder() {
    return getErr();
  }

  public static final int DOC_FIELD_NUMBER = 2;
  private Document doc_;
  /**
   * <code>.Document doc = 2;</code>
   * @return Whether the doc field is set.
   */
  @Override
  public boolean hasDoc() {
    return doc_ != null;
  }
  /**
   * <code>.Document doc = 2;</code>
   * @return The doc.
   */
  @Override
  public Document getDoc() {
    return doc_ == null ? Document.getDefaultInstance() : doc_;
  }
  /**
   * <code>.Document doc = 2;</code>
   */
  @Override
  public DocumentOrBuilder getDocOrBuilder() {
    return getDoc();
  }

  public static final int MSG_FIELD_NUMBER = 3;
  private volatile Object msg_;
  /**
   * <code>string msg = 3;</code>
   * @return The msg.
   */
  @Override
  public String getMsg() {
    Object ref = msg_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <code>string msg = 3;</code>
   * @return The bytes for msg.
   */
  @Override
  public com.google.protobuf.ByteString
      getMsgBytes() {
    Object ref = msg_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (err_ != null) {
      output.writeMessage(1, getErr());
    }
    if (doc_ != null) {
      output.writeMessage(2, getDoc());
    }
    if (!getMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (err_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getErr());
    }
    if (doc_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDoc());
    }
    if (!getMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Item)) {
      return super.equals(obj);
    }
    Item other = (Item) obj;

    if (hasErr() != other.hasErr()) return false;
    if (hasErr()) {
      if (!getErr()
          .equals(other.getErr())) return false;
    }
    if (hasDoc() != other.hasDoc()) return false;
    if (hasDoc()) {
      if (!getDoc()
          .equals(other.getDoc())) return false;
    }
    if (!getMsg()
        .equals(other.getMsg())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasErr()) {
      hash = (37 * hash) + ERR_FIELD_NUMBER;
      hash = (53 * hash) + getErr().hashCode();
    }
    if (hasDoc()) {
      hash = (37 * hash) + DOC_FIELD_NUMBER;
      hash = (53 * hash) + getDoc().hashCode();
    }
    hash = (37 * hash) + MSG_FIELD_NUMBER;
    hash = (53 * hash) + getMsg().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Item parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Item parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Item parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Item parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Item parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Item parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Item parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Item parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Item parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Item parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Item parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Item parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Item prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Item}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Item)
      ItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataModel.internal_static_Item_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataModel.internal_static_Item_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Item.class, Item.Builder.class);
    }

    // Construct using com.vearch.grpc.entity.Item.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (errBuilder_ == null) {
        err_ = null;
      } else {
        err_ = null;
        errBuilder_ = null;
      }
      if (docBuilder_ == null) {
        doc_ = null;
      } else {
        doc_ = null;
        docBuilder_ = null;
      }
      msg_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DataModel.internal_static_Item_descriptor;
    }

    @Override
    public Item getDefaultInstanceForType() {
      return Item.getDefaultInstance();
    }

    @Override
    public Item build() {
      Item result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Item buildPartial() {
      Item result = new Item(this);
      if (errBuilder_ == null) {
        result.err_ = err_;
      } else {
        result.err_ = errBuilder_.build();
      }
      if (docBuilder_ == null) {
        result.doc_ = doc_;
      } else {
        result.doc_ = docBuilder_.build();
      }
      result.msg_ = msg_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Item) {
        return mergeFrom((Item)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Item other) {
      if (other == Item.getDefaultInstance()) return this;
      if (other.hasErr()) {
        mergeErr(other.getErr());
      }
      if (other.hasDoc()) {
        mergeDoc(other.getDoc());
      }
      if (!other.getMsg().isEmpty()) {
        msg_ = other.msg_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Item parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Item) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Error err_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Error, Error.Builder, ErrorOrBuilder> errBuilder_;
    /**
     * <code>.Error err = 1;</code>
     * @return Whether the err field is set.
     */
    public boolean hasErr() {
      return errBuilder_ != null || err_ != null;
    }
    /**
     * <code>.Error err = 1;</code>
     * @return The err.
     */
    public Error getErr() {
      if (errBuilder_ == null) {
        return err_ == null ? Error.getDefaultInstance() : err_;
      } else {
        return errBuilder_.getMessage();
      }
    }
    /**
     * <code>.Error err = 1;</code>
     */
    public Builder setErr(Error value) {
      if (errBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        err_ = value;
        onChanged();
      } else {
        errBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Error err = 1;</code>
     */
    public Builder setErr(
        Error.Builder builderForValue) {
      if (errBuilder_ == null) {
        err_ = builderForValue.build();
        onChanged();
      } else {
        errBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Error err = 1;</code>
     */
    public Builder mergeErr(Error value) {
      if (errBuilder_ == null) {
        if (err_ != null) {
          err_ =
            Error.newBuilder(err_).mergeFrom(value).buildPartial();
        } else {
          err_ = value;
        }
        onChanged();
      } else {
        errBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Error err = 1;</code>
     */
    public Builder clearErr() {
      if (errBuilder_ == null) {
        err_ = null;
        onChanged();
      } else {
        err_ = null;
        errBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Error err = 1;</code>
     */
    public Error.Builder getErrBuilder() {

      onChanged();
      return getErrFieldBuilder().getBuilder();
    }
    /**
     * <code>.Error err = 1;</code>
     */
    public ErrorOrBuilder getErrOrBuilder() {
      if (errBuilder_ != null) {
        return errBuilder_.getMessageOrBuilder();
      } else {
        return err_ == null ?
            Error.getDefaultInstance() : err_;
      }
    }
    /**
     * <code>.Error err = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Error, Error.Builder, ErrorOrBuilder>
        getErrFieldBuilder() {
      if (errBuilder_ == null) {
        errBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Error, Error.Builder, ErrorOrBuilder>(
                getErr(),
                getParentForChildren(),
                isClean());
        err_ = null;
      }
      return errBuilder_;
    }

    private Document doc_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Document, Document.Builder, DocumentOrBuilder> docBuilder_;
    /**
     * <code>.Document doc = 2;</code>
     * @return Whether the doc field is set.
     */
    public boolean hasDoc() {
      return docBuilder_ != null || doc_ != null;
    }
    /**
     * <code>.Document doc = 2;</code>
     * @return The doc.
     */
    public Document getDoc() {
      if (docBuilder_ == null) {
        return doc_ == null ? Document.getDefaultInstance() : doc_;
      } else {
        return docBuilder_.getMessage();
      }
    }
    /**
     * <code>.Document doc = 2;</code>
     */
    public Builder setDoc(Document value) {
      if (docBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        doc_ = value;
        onChanged();
      } else {
        docBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Document doc = 2;</code>
     */
    public Builder setDoc(
        Document.Builder builderForValue) {
      if (docBuilder_ == null) {
        doc_ = builderForValue.build();
        onChanged();
      } else {
        docBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Document doc = 2;</code>
     */
    public Builder mergeDoc(Document value) {
      if (docBuilder_ == null) {
        if (doc_ != null) {
          doc_ =
            Document.newBuilder(doc_).mergeFrom(value).buildPartial();
        } else {
          doc_ = value;
        }
        onChanged();
      } else {
        docBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Document doc = 2;</code>
     */
    public Builder clearDoc() {
      if (docBuilder_ == null) {
        doc_ = null;
        onChanged();
      } else {
        doc_ = null;
        docBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Document doc = 2;</code>
     */
    public Document.Builder getDocBuilder() {

      onChanged();
      return getDocFieldBuilder().getBuilder();
    }
    /**
     * <code>.Document doc = 2;</code>
     */
    public DocumentOrBuilder getDocOrBuilder() {
      if (docBuilder_ != null) {
        return docBuilder_.getMessageOrBuilder();
      } else {
        return doc_ == null ?
            Document.getDefaultInstance() : doc_;
      }
    }
    /**
     * <code>.Document doc = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Document, Document.Builder, DocumentOrBuilder>
        getDocFieldBuilder() {
      if (docBuilder_ == null) {
        docBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Document, Document.Builder, DocumentOrBuilder>(
                getDoc(),
                getParentForChildren(),
                isClean());
        doc_ = null;
      }
      return docBuilder_;
    }

    private Object msg_ = "";
    /**
     * <code>string msg = 3;</code>
     * @return The msg.
     */
    public String getMsg() {
      Object ref = msg_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string msg = 3;</code>
     * @return The bytes for msg.
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg = 3;</code>
     * @param value The msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsg(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      msg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsg() {

      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 3;</code>
     * @param value The bytes for msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      msg_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Item)
  }

  // @@protoc_insertion_point(class_scope:Item)
  private static final Item DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Item();
  }

  public static Item getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Item>
      PARSER = new com.google.protobuf.AbstractParser<Item>() {
    @Override
    public Item parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Item(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Item> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Item> getParserForType() {
    return PARSER;
  }

  @Override
  public Item getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

