// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_model.proto

package com.vearch.grpc.entity;

public interface ItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Item)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Error err = 1;</code>
   * @return Whether the err field is set.
   */
  boolean hasErr();
  /**
   * <code>.Error err = 1;</code>
   * @return The err.
   */
  Error getErr();
  /**
   * <code>.Error err = 1;</code>
   */
  ErrorOrBuilder getErrOrBuilder();

  /**
   * <code>.Document doc = 2;</code>
   * @return Whether the doc field is set.
   */
  boolean hasDoc();
  /**
   * <code>.Document doc = 2;</code>
   * @return The doc.
   */
  Document getDoc();
  /**
   * <code>.Document doc = 2;</code>
   */
  DocumentOrBuilder getDocOrBuilder();

  /**
   * <code>string msg = 3;</code>
   * @return The msg.
   */
  String getMsg();
  /**
   * <code>string msg = 3;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
