// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router_grpc.proto

package com.vearch.grpc.entity;

public interface RequestHeadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestHead)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 time_out_ms = 1;</code>
   * @return The timeOutMs.
   */
  long getTimeOutMs();

  /**
   * <code>string user_name = 2;</code>
   * @return The userName.
   */
  String getUserName();
  /**
   * <code>string user_name = 2;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string db_name = 4;</code>
   * @return The dbName.
   */
  String getDbName();
  /**
   * <code>string db_name = 4;</code>
   * @return The bytes for dbName.
   */
  com.google.protobuf.ByteString
      getDbNameBytes();

  /**
   * <code>string space_name = 5;</code>
   * @return The spaceName.
   */
  String getSpaceName();
  /**
   * <code>string space_name = 5;</code>
   * @return The bytes for spaceName.
   */
  com.google.protobuf.ByteString
      getSpaceNameBytes();

  /**
   * <code>string client_type = 6;</code>
   * @return The clientType.
   */
  String getClientType();
  /**
   * <code>string client_type = 6;</code>
   * @return The bytes for clientType.
   */
  com.google.protobuf.ByteString
      getClientTypeBytes();

  /**
   * <pre>
   * from, sort, request_id, partition_id
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 7;</code>
   */
  int getParamsCount();
  /**
   * <pre>
   * from, sort, request_id, partition_id
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 7;</code>
   */
  boolean containsParams(
          String key);
  /**
   * Use {@link #getParamsMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getParams();
  /**
   * <pre>
   * from, sort, request_id, partition_id
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 7;</code>
   */
  java.util.Map<String, String>
  getParamsMap();
  /**
   * <pre>
   * from, sort, request_id, partition_id
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 7;</code>
   */

  String getParamsOrDefault(
          String key,
          String defaultValue);
  /**
   * <pre>
   * from, sort, request_id, partition_id
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 7;</code>
   */

  String getParamsOrThrow(
          String key);

  /**
   * <code>bool leader = 8;</code>
   * @return The leader.
   */
  boolean getLeader();
}
