// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router_grpc.proto

package com.vearch.grpc.entity;

/**
 * Protobuf type {@code RequestHead}
 */
public final class RequestHead extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RequestHead)
    RequestHeadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestHead.newBuilder() to construct.
  private RequestHead(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestHead() {
    userName_ = "";
    password_ = "";
    dbName_ = "";
    spaceName_ = "";
    clientType_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestHead();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestHead(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            timeOutMs_ = input.readInt64();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            userName_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            dbName_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            spaceName_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            clientType_ = s;
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              params_ = com.google.protobuf.MapField.newMapField(
                  ParamsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<String, String>
            params__ = input.readMessage(
                ParamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            params_.getMutableMap().put(
                params__.getKey(), params__.getValue());
            break;
          }
          case 64: {

            leader_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RouterGrpc.internal_static_RequestHead_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 7:
        return internalGetParams();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RouterGrpc.internal_static_RequestHead_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RequestHead.class, RequestHead.Builder.class);
  }

  public static final int TIME_OUT_MS_FIELD_NUMBER = 1;
  private long timeOutMs_;
  /**
   * <code>int64 time_out_ms = 1;</code>
   * @return The timeOutMs.
   */
  @Override
  public long getTimeOutMs() {
    return timeOutMs_;
  }

  public static final int USER_NAME_FIELD_NUMBER = 2;
  private volatile Object userName_;
  /**
   * <code>string user_name = 2;</code>
   * @return The userName.
   */
  @Override
  public String getUserName() {
    Object ref = userName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string user_name = 2;</code>
   * @return The bytes for userName.
   */
  @Override
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    Object ref = userName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  private volatile Object password_;
  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  @Override
  public String getPassword() {
    Object ref = password_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  @Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    Object ref = password_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DB_NAME_FIELD_NUMBER = 4;
  private volatile Object dbName_;
  /**
   * <code>string db_name = 4;</code>
   * @return The dbName.
   */
  @Override
  public String getDbName() {
    Object ref = dbName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dbName_ = s;
      return s;
    }
  }
  /**
   * <code>string db_name = 4;</code>
   * @return The bytes for dbName.
   */
  @Override
  public com.google.protobuf.ByteString
      getDbNameBytes() {
    Object ref = dbName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dbName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPACE_NAME_FIELD_NUMBER = 5;
  private volatile Object spaceName_;
  /**
   * <code>string space_name = 5;</code>
   * @return The spaceName.
   */
  @Override
  public String getSpaceName() {
    Object ref = spaceName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      spaceName_ = s;
      return s;
    }
  }
  /**
   * <code>string space_name = 5;</code>
   * @return The bytes for spaceName.
   */
  @Override
  public com.google.protobuf.ByteString
      getSpaceNameBytes() {
    Object ref = spaceName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      spaceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_TYPE_FIELD_NUMBER = 6;
  private volatile Object clientType_;
  /**
   * <code>string client_type = 6;</code>
   * @return The clientType.
   */
  @Override
  public String getClientType() {
    Object ref = clientType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      clientType_ = s;
      return s;
    }
  }
  /**
   * <code>string client_type = 6;</code>
   * @return The bytes for clientType.
   */
  @Override
  public com.google.protobuf.ByteString
      getClientTypeBytes() {
    Object ref = clientType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      clientType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMS_FIELD_NUMBER = 7;
  private static final class ParamsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                RouterGrpc.internal_static_RequestHead_ParamsEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      String, String> params_;
  private com.google.protobuf.MapField<String, String>
  internalGetParams() {
    if (params_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ParamsDefaultEntryHolder.defaultEntry);
    }
    return params_;
  }

  public int getParamsCount() {
    return internalGetParams().getMap().size();
  }
  /**
   * <pre>
   * from, sort, request_id, partition_id
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 7;</code>
   */

  @Override
  public boolean containsParams(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    return internalGetParams().getMap().containsKey(key);
  }
  /**
   * Use {@link #getParamsMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, String> getParams() {
    return getParamsMap();
  }
  /**
   * <pre>
   * from, sort, request_id, partition_id
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 7;</code>
   */
  @Override

  public java.util.Map<String, String> getParamsMap() {
    return internalGetParams().getMap();
  }
  /**
   * <pre>
   * from, sort, request_id, partition_id
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 7;</code>
   */
  @Override

  public String getParamsOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, String> map =
        internalGetParams().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * from, sort, request_id, partition_id
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 7;</code>
   */
  @Override

  public String getParamsOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, String> map =
        internalGetParams().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int LEADER_FIELD_NUMBER = 8;
  private boolean leader_;
  /**
   * <code>bool leader = 8;</code>
   * @return The leader.
   */
  @Override
  public boolean getLeader() {
    return leader_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timeOutMs_ != 0L) {
      output.writeInt64(1, timeOutMs_);
    }
    if (!getUserNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
    }
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
    }
    if (!getDbNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dbName_);
    }
    if (!getSpaceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, spaceName_);
    }
    if (!getClientTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, clientType_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetParams(),
        ParamsDefaultEntryHolder.defaultEntry,
        7);
    if (leader_ != false) {
      output.writeBool(8, leader_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timeOutMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timeOutMs_);
    }
    if (!getUserNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
    }
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
    }
    if (!getDbNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dbName_);
    }
    if (!getSpaceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, spaceName_);
    }
    if (!getClientTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, clientType_);
    }
    for (java.util.Map.Entry<String, String> entry
         : internalGetParams().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      params__ = ParamsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, params__);
    }
    if (leader_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, leader_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RequestHead)) {
      return super.equals(obj);
    }
    RequestHead other = (RequestHead) obj;

    if (getTimeOutMs()
        != other.getTimeOutMs()) return false;
    if (!getUserName()
        .equals(other.getUserName())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (!getDbName()
        .equals(other.getDbName())) return false;
    if (!getSpaceName()
        .equals(other.getSpaceName())) return false;
    if (!getClientType()
        .equals(other.getClientType())) return false;
    if (!internalGetParams().equals(
        other.internalGetParams())) return false;
    if (getLeader()
        != other.getLeader()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_OUT_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeOutMs());
    hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + DB_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getDbName().hashCode();
    hash = (37 * hash) + SPACE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getSpaceName().hashCode();
    hash = (37 * hash) + CLIENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getClientType().hashCode();
    if (!internalGetParams().getMap().isEmpty()) {
      hash = (37 * hash) + PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetParams().hashCode();
    }
    hash = (37 * hash) + LEADER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLeader());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RequestHead parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RequestHead parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RequestHead parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RequestHead parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RequestHead parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RequestHead parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RequestHead parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RequestHead parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RequestHead parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RequestHead parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RequestHead parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RequestHead parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RequestHead prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RequestHead}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RequestHead)
      RequestHeadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RouterGrpc.internal_static_RequestHead_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetMutableParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RouterGrpc.internal_static_RequestHead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestHead.class, RequestHead.Builder.class);
    }

    // Construct using com.vearch.grpc.entity.RequestHead.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      timeOutMs_ = 0L;

      userName_ = "";

      password_ = "";

      dbName_ = "";

      spaceName_ = "";

      clientType_ = "";

      internalGetMutableParams().clear();
      leader_ = false;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RouterGrpc.internal_static_RequestHead_descriptor;
    }

    @Override
    public RequestHead getDefaultInstanceForType() {
      return RequestHead.getDefaultInstance();
    }

    @Override
    public RequestHead build() {
      RequestHead result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public RequestHead buildPartial() {
      RequestHead result = new RequestHead(this);
      int from_bitField0_ = bitField0_;
      result.timeOutMs_ = timeOutMs_;
      result.userName_ = userName_;
      result.password_ = password_;
      result.dbName_ = dbName_;
      result.spaceName_ = spaceName_;
      result.clientType_ = clientType_;
      result.params_ = internalGetParams();
      result.params_.makeImmutable();
      result.leader_ = leader_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RequestHead) {
        return mergeFrom((RequestHead)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RequestHead other) {
      if (other == RequestHead.getDefaultInstance()) return this;
      if (other.getTimeOutMs() != 0L) {
        setTimeOutMs(other.getTimeOutMs());
      }
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (!other.getDbName().isEmpty()) {
        dbName_ = other.dbName_;
        onChanged();
      }
      if (!other.getSpaceName().isEmpty()) {
        spaceName_ = other.spaceName_;
        onChanged();
      }
      if (!other.getClientType().isEmpty()) {
        clientType_ = other.clientType_;
        onChanged();
      }
      internalGetMutableParams().mergeFrom(
          other.internalGetParams());
      if (other.getLeader() != false) {
        setLeader(other.getLeader());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RequestHead parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RequestHead) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long timeOutMs_ ;
    /**
     * <code>int64 time_out_ms = 1;</code>
     * @return The timeOutMs.
     */
    @Override
    public long getTimeOutMs() {
      return timeOutMs_;
    }
    /**
     * <code>int64 time_out_ms = 1;</code>
     * @param value The timeOutMs to set.
     * @return This builder for chaining.
     */
    public Builder setTimeOutMs(long value) {

      timeOutMs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 time_out_ms = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeOutMs() {

      timeOutMs_ = 0L;
      onChanged();
      return this;
    }

    private Object userName_ = "";
    /**
     * <code>string user_name = 2;</code>
     * @return The userName.
     */
    public String getUserName() {
      Object ref = userName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string user_name = 2;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_name = 2;</code>
     * @param value The userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserName() {

      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string user_name = 2;</code>
     * @param value The bytes for userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      userName_ = value;
      onChanged();
      return this;
    }

    private Object password_ = "";
    /**
     * <code>string password = 3;</code>
     * @return The password.
     */
    public String getPassword() {
      Object ref = password_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {

      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      password_ = value;
      onChanged();
      return this;
    }

    private Object dbName_ = "";
    /**
     * <code>string db_name = 4;</code>
     * @return The dbName.
     */
    public String getDbName() {
      Object ref = dbName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dbName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string db_name = 4;</code>
     * @return The bytes for dbName.
     */
    public com.google.protobuf.ByteString
        getDbNameBytes() {
      Object ref = dbName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dbName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string db_name = 4;</code>
     * @param value The dbName to set.
     * @return This builder for chaining.
     */
    public Builder setDbName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      dbName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string db_name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDbName() {

      dbName_ = getDefaultInstance().getDbName();
      onChanged();
      return this;
    }
    /**
     * <code>string db_name = 4;</code>
     * @param value The bytes for dbName to set.
     * @return This builder for chaining.
     */
    public Builder setDbNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      dbName_ = value;
      onChanged();
      return this;
    }

    private Object spaceName_ = "";
    /**
     * <code>string space_name = 5;</code>
     * @return The spaceName.
     */
    public String getSpaceName() {
      Object ref = spaceName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        spaceName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string space_name = 5;</code>
     * @return The bytes for spaceName.
     */
    public com.google.protobuf.ByteString
        getSpaceNameBytes() {
      Object ref = spaceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        spaceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string space_name = 5;</code>
     * @param value The spaceName to set.
     * @return This builder for chaining.
     */
    public Builder setSpaceName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      spaceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string space_name = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpaceName() {

      spaceName_ = getDefaultInstance().getSpaceName();
      onChanged();
      return this;
    }
    /**
     * <code>string space_name = 5;</code>
     * @param value The bytes for spaceName to set.
     * @return This builder for chaining.
     */
    public Builder setSpaceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      spaceName_ = value;
      onChanged();
      return this;
    }

    private Object clientType_ = "";
    /**
     * <code>string client_type = 6;</code>
     * @return The clientType.
     */
    public String getClientType() {
      Object ref = clientType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string client_type = 6;</code>
     * @return The bytes for clientType.
     */
    public com.google.protobuf.ByteString
        getClientTypeBytes() {
      Object ref = clientType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_type = 6;</code>
     * @param value The clientType to set.
     * @return This builder for chaining.
     */
    public Builder setClientType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      clientType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string client_type = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientType() {

      clientType_ = getDefaultInstance().getClientType();
      onChanged();
      return this;
    }
    /**
     * <code>string client_type = 6;</code>
     * @param value The bytes for clientType to set.
     * @return This builder for chaining.
     */
    public Builder setClientTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      clientType_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        String, String> params_;
    private com.google.protobuf.MapField<String, String>
    internalGetParams() {
      if (params_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ParamsDefaultEntryHolder.defaultEntry);
      }
      return params_;
    }
    private com.google.protobuf.MapField<String, String>
    internalGetMutableParams() {
      onChanged();;
      if (params_ == null) {
        params_ = com.google.protobuf.MapField.newMapField(
            ParamsDefaultEntryHolder.defaultEntry);
      }
      if (!params_.isMutable()) {
        params_ = params_.copy();
      }
      return params_;
    }

    public int getParamsCount() {
      return internalGetParams().getMap().size();
    }
    /**
     * <pre>
     * from, sort, request_id, partition_id
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */

    @Override
    public boolean containsParams(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetParams().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParamsMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getParams() {
      return getParamsMap();
    }
    /**
     * <pre>
     * from, sort, request_id, partition_id
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */
    @Override

    public java.util.Map<String, String> getParamsMap() {
      return internalGetParams().getMap();
    }
    /**
     * <pre>
     * from, sort, request_id, partition_id
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */
    @Override

    public String getParamsOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetParams().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * from, sort, request_id, partition_id
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */
    @Override

    public String getParamsOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetParams().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearParams() {
      internalGetMutableParams().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * from, sort, request_id, partition_id
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */

    public Builder removeParams(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      internalGetMutableParams().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableParams() {
      return internalGetMutableParams().getMutableMap();
    }
    /**
     * <pre>
     * from, sort, request_id, partition_id
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */
    public Builder putParams(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException(); }
      if (value == null) { throw new NullPointerException(); }
      internalGetMutableParams().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * from, sort, request_id, partition_id
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */

    public Builder putAllParams(
        java.util.Map<String, String> values) {
      internalGetMutableParams().getMutableMap()
          .putAll(values);
      return this;
    }

    private boolean leader_ ;
    /**
     * <code>bool leader = 8;</code>
     * @return The leader.
     */
    @Override
    public boolean getLeader() {
      return leader_;
    }
    /**
     * <code>bool leader = 8;</code>
     * @param value The leader to set.
     * @return This builder for chaining.
     */
    public Builder setLeader(boolean value) {

      leader_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool leader = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeader() {

      leader_ = false;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RequestHead)
  }

  // @@protoc_insertion_point(class_scope:RequestHead)
  private static final RequestHead DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RequestHead();
  }

  public static RequestHead getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestHead>
      PARSER = new com.google.protobuf.AbstractParser<RequestHead>() {
    @Override
    public RequestHead parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestHead(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestHead> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RequestHead> getParserForType() {
    return PARSER;
  }

  @Override
  public RequestHead getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

