// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router_grpc.proto

package com.vearch.grpc.entity;

/**
 * Protobuf type {@code RetrievalParameters}
 */
public final class RetrievalParameters extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RetrievalParameters)
    RetrievalParametersOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RetrievalParameters.newBuilder() to construct.
  private RetrievalParameters(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RetrievalParameters() {
    metricType_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new RetrievalParameters();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RetrievalParameters(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            metricType_ = rawValue;
            break;
          }
          case 16: {

            nprobe_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RouterGrpc.internal_static_RetrievalParameters_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RouterGrpc.internal_static_RetrievalParameters_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RetrievalParameters.class, RetrievalParameters.Builder.class);
  }

  /**
   * Protobuf enum {@code RetrievalParameters.DistanceMetricType}
   */
  public enum DistanceMetricType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>InnerProduct = 0;</code>
     */
    InnerProduct(0),
    /**
     * <code>L2 = 1;</code>
     */
    L2(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>InnerProduct = 0;</code>
     */
    public static final int InnerProduct_VALUE = 0;
    /**
     * <code>L2 = 1;</code>
     */
    public static final int L2_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static DistanceMetricType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DistanceMetricType forNumber(int value) {
      switch (value) {
        case 0: return InnerProduct;
        case 1: return L2;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DistanceMetricType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DistanceMetricType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DistanceMetricType>() {
            public DistanceMetricType findValueByNumber(int number) {
              return DistanceMetricType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return RetrievalParameters.getDescriptor().getEnumTypes().get(0);
    }

    private static final DistanceMetricType[] VALUES = values();

    public static DistanceMetricType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DistanceMetricType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RetrievalParameters.DistanceMetricType)
  }

  public static final int METRIC_TYPE_FIELD_NUMBER = 1;
  private int metricType_;
  /**
   * <code>.RetrievalParameters.DistanceMetricType metric_type = 1;</code>
   * @return The enum numeric value on the wire for metricType.
   */
  @Override public int getMetricTypeValue() {
    return metricType_;
  }
  /**
   * <code>.RetrievalParameters.DistanceMetricType metric_type = 1;</code>
   * @return The metricType.
   */
  @Override public RetrievalParameters.DistanceMetricType getMetricType() {
    @SuppressWarnings("deprecation")
    RetrievalParameters.DistanceMetricType result = RetrievalParameters.DistanceMetricType.valueOf(metricType_);
    return result == null ? RetrievalParameters.DistanceMetricType.UNRECOGNIZED : result;
  }

  public static final int NPROBE_FIELD_NUMBER = 2;
  private int nprobe_;
  /**
   * <code>int32 nprobe = 2;</code>
   * @return The nprobe.
   */
  @Override
  public int getNprobe() {
    return nprobe_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (metricType_ != RetrievalParameters.DistanceMetricType.InnerProduct.getNumber()) {
      output.writeEnum(1, metricType_);
    }
    if (nprobe_ != 0) {
      output.writeInt32(2, nprobe_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (metricType_ != RetrievalParameters.DistanceMetricType.InnerProduct.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, metricType_);
    }
    if (nprobe_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, nprobe_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RetrievalParameters)) {
      return super.equals(obj);
    }
    RetrievalParameters other = (RetrievalParameters) obj;

    if (metricType_ != other.metricType_) return false;
    if (getNprobe()
        != other.getNprobe()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + METRIC_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + metricType_;
    hash = (37 * hash) + NPROBE_FIELD_NUMBER;
    hash = (53 * hash) + getNprobe();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RetrievalParameters parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RetrievalParameters parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RetrievalParameters parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RetrievalParameters parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RetrievalParameters parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RetrievalParameters parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RetrievalParameters parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RetrievalParameters parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RetrievalParameters parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RetrievalParameters parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RetrievalParameters parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RetrievalParameters parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RetrievalParameters prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RetrievalParameters}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RetrievalParameters)
      RetrievalParametersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RouterGrpc.internal_static_RetrievalParameters_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RouterGrpc.internal_static_RetrievalParameters_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RetrievalParameters.class, RetrievalParameters.Builder.class);
    }

    // Construct using com.vearch.grpc.entity.RetrievalParameters.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      metricType_ = 0;

      nprobe_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RouterGrpc.internal_static_RetrievalParameters_descriptor;
    }

    @Override
    public RetrievalParameters getDefaultInstanceForType() {
      return RetrievalParameters.getDefaultInstance();
    }

    @Override
    public RetrievalParameters build() {
      RetrievalParameters result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public RetrievalParameters buildPartial() {
      RetrievalParameters result = new RetrievalParameters(this);
      result.metricType_ = metricType_;
      result.nprobe_ = nprobe_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RetrievalParameters) {
        return mergeFrom((RetrievalParameters)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RetrievalParameters other) {
      if (other == RetrievalParameters.getDefaultInstance()) return this;
      if (other.metricType_ != 0) {
        setMetricTypeValue(other.getMetricTypeValue());
      }
      if (other.getNprobe() != 0) {
        setNprobe(other.getNprobe());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RetrievalParameters parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RetrievalParameters) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int metricType_ = 0;
    /**
     * <code>.RetrievalParameters.DistanceMetricType metric_type = 1;</code>
     * @return The enum numeric value on the wire for metricType.
     */
    @Override public int getMetricTypeValue() {
      return metricType_;
    }
    /**
     * <code>.RetrievalParameters.DistanceMetricType metric_type = 1;</code>
     * @param value The enum numeric value on the wire for metricType to set.
     * @return This builder for chaining.
     */
    public Builder setMetricTypeValue(int value) {

      metricType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.RetrievalParameters.DistanceMetricType metric_type = 1;</code>
     * @return The metricType.
     */
    @Override
    public RetrievalParameters.DistanceMetricType getMetricType() {
      @SuppressWarnings("deprecation")
      RetrievalParameters.DistanceMetricType result = RetrievalParameters.DistanceMetricType.valueOf(metricType_);
      return result == null ? RetrievalParameters.DistanceMetricType.UNRECOGNIZED : result;
    }
    /**
     * <code>.RetrievalParameters.DistanceMetricType metric_type = 1;</code>
     * @param value The metricType to set.
     * @return This builder for chaining.
     */
    public Builder setMetricType(RetrievalParameters.DistanceMetricType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      metricType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.RetrievalParameters.DistanceMetricType metric_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetricType() {

      metricType_ = 0;
      onChanged();
      return this;
    }

    private int nprobe_ ;
    /**
     * <code>int32 nprobe = 2;</code>
     * @return The nprobe.
     */
    @Override
    public int getNprobe() {
      return nprobe_;
    }
    /**
     * <code>int32 nprobe = 2;</code>
     * @param value The nprobe to set.
     * @return This builder for chaining.
     */
    public Builder setNprobe(int value) {

      nprobe_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nprobe = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNprobe() {

      nprobe_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RetrievalParameters)
  }

  // @@protoc_insertion_point(class_scope:RetrievalParameters)
  private static final RetrievalParameters DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RetrievalParameters();
  }

  public static RetrievalParameters getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RetrievalParameters>
      PARSER = new com.google.protobuf.AbstractParser<RetrievalParameters>() {
    @Override
    public RetrievalParameters parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RetrievalParameters(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RetrievalParameters> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RetrievalParameters> getParserForType() {
    return PARSER;
  }

  @Override
  public RetrievalParameters getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

