// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router_grpc.proto

package com.vearch.grpc.entity;

public final class RouterGrpc {
  private RouterGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestHead_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestHead_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestHead_ParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestHead_ParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseHead_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseHead_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseHead_ParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseHead_ParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BulkRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BulkRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ForceMergeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ForceMergeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BulkResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BulkResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ForceMergeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ForceMergeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DelByQueryeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DelByQueryeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TermFilter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TermFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RangeFilter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RangeFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SortField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SortField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VectorQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VectorQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RetrievalParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RetrievalParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchRequest_SortFieldMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchRequest_SortFieldMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResultItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchResult_ExplainEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchResult_ExplainEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchResponse_SortFieldMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchResponse_SortFieldMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MSearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MSearchRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021router_grpc.proto\032\020data_model.proto\032\014e" +
      "rrors.proto\"\352\001\n\013RequestHead\022\023\n\013time_out_" +
      "ms\030\001 \001(\003\022\021\n\tuser_name\030\002 \001(\t\022\020\n\010password\030" +
      "\003 \001(\t\022\017\n\007db_name\030\004 \001(\t\022\022\n\nspace_name\030\005 \001" +
      "(\t\022\023\n\013client_type\030\006 \001(\t\022(\n\006params\030\007 \003(\0132" +
      "\030.RequestHead.ParamsEntry\022\016\n\006leader\030\010 \001(" +
      "\010\032-\n\013ParamsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001\"}\n\014ResponseHead\022\023\n\003err\030\001 \001(\0132\006." +
      "Error\022)\n\006params\030\003 \003(\0132\031.ResponseHead.Par" +
      "amsEntry\032-\n\013ParamsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\t:\0028\001\">\n\nGetRequest\022\032\n\004head\030\001 " +
      "\001(\0132\014.RequestHead\022\024\n\014primary_keys\030\004 \003(\t\"" +
      "A\n\rDeleteRequest\022\032\n\004head\030\001 \001(\0132\014.Request" +
      "Head\022\024\n\014primary_keys\030\004 \003(\t\"@\n\nAddRequest" +
      "\022\032\n\004head\030\001 \001(\0132\014.RequestHead\022\026\n\003doc\030\004 \001(" +
      "\0132\t.Document\"C\n\rUpdateRequest\022\032\n\004head\030\001 " +
      "\001(\0132\014.RequestHead\022\026\n\003doc\030\004 \001(\0132\t.Documen" +
      "t\"B\n\013BulkRequest\022\032\n\004head\030\001 \001(\0132\014.Request" +
      "Head\022\027\n\004docs\030\004 \003(\0132\t.Document\"/\n\021ForceMe" +
      "rgeRequest\022\032\n\004head\030\001 \001(\0132\014.RequestHead\"@" +
      "\n\013GetResponse\022\033\n\004head\030\001 \001(\0132\r.ResponseHe" +
      "ad\022\024\n\005items\030\002 \003(\0132\005.Item\"?\n\013AddResponse\022" +
      "\033\n\004head\030\001 \001(\0132\r.ResponseHead\022\023\n\013primary_" +
      "key\030\004 \001(\t\"-\n\016UpdateResponse\022\033\n\004head\030\001 \001(" +
      "\0132\r.ResponseHead\"C\n\016DeleteResponse\022\033\n\004he" +
      "ad\030\001 \001(\0132\r.ResponseHead\022\024\n\005items\030\002 \003(\0132\005" +
      ".Item\"A\n\014BulkResponse\022\033\n\004head\030\001 \001(\0132\r.Re" +
      "sponseHead\022\024\n\005items\030\002 \003(\0132\005.Item\"P\n\022Forc" +
      "eMergeResponse\022\033\n\004head\030\001 \001(\0132\r.ResponseH" +
      "ead\022\035\n\006shards\030\002 \001(\0132\r.SearchStatus\"B\n\023De" +
      "lByQueryeResponse\022\033\n\004head\030\001 \001(\0132\r.Respon" +
      "seHead\022\016\n\006DelNum\030\002 \001(\005\"<\n\nTermFilter\022\r\n\005" +
      "field\030\001 \001(\t\022\r\n\005value\030\002 \001(\014\022\020\n\010is_union\030\003" +
      " \001(\005\"t\n\013RangeFilter\022\r\n\005field\030\001 \001(\t\022\023\n\013lo" +
      "wer_value\030\002 \001(\014\022\023\n\013upper_value\030\003 \001(\014\022\025\n\r" +
      "include_lower\030\004 \001(\010\022\025\n\rinclude_upper\030\005 \001" +
      "(\010\"(\n\tSortField\022\r\n\005field\030\001 \001(\t\022\014\n\004type\030\002" +
      " \001(\010\"r\n\013VectorQuery\022\014\n\004name\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\014\022\021\n\tmin_score\030\003 \001(\001\022\021\n\tmax_score" +
      "\030\004 \001(\001\022\r\n\005boost\030\005 \001(\001\022\021\n\thas_boost\030\006 \001(\005" +
      "\"\223\001\n\023RetrievalParameters\022<\n\013metric_type\030" +
      "\001 \001(\0162\'.RetrievalParameters.DistanceMetr" +
      "icType\022\016\n\006nprobe\030\002 \001(\005\".\n\022DistanceMetric" +
      "Type\022\020\n\014InnerProduct\020\000\022\006\n\002L2\020\001\"\253\004\n\rSearc" +
      "hRequest\022\032\n\004head\030\001 \001(\0132\014.RequestHead\022\017\n\007" +
      "req_num\030\002 \001(\005\022\014\n\004topN\030\003 \001(\005\022\027\n\017is_brute_" +
      "search\030\004 \001(\005\022 \n\nvec_fields\030\005 \003(\0132\014.Vecto" +
      "rQuery\022\016\n\006fields\030\006 \003(\t\022#\n\rrange_filters\030" +
      "\007 \003(\0132\014.RangeFilter\022!\n\014term_filters\030\010 \003(" +
      "\0132\013.TermFilter\022\030\n\020online_log_level\030\t \001(\t" +
      "\022\030\n\020retrieval_params\030\n \001(\t\022\020\n\010has_rank\030\013" +
      " \001(\010\022\031\n\021multi_vector_rank\030\014 \001(\005\022\037\n\027paral" +
      "lel_based_on_query\030\r \001(\010\022\017\n\007l2_sqrt\030\016 \001(" +
      "\010\022\020\n\010ivf_flat\030\017 \001(\010\022\027\n\017is_vector_value\030\020" +
      " \001(\010\0228\n\016sort_field_map\030\021 \003(\0132 .SearchReq" +
      "uest.SortFieldMapEntry\022\037\n\013sort_fields\030\022 " +
      "\003(\0132\n.SortField\0323\n\021SortFieldMapEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"a\n\nResultIt" +
      "em\022\r\n\005score\030\001 \001(\001\022\026\n\006fields\030\002 \003(\0132\006.Fiel" +
      "d\022\r\n\005extra\030\003 \001(\t\022\r\n\005p_key\030\004 \001(\t\022\016\n\006sourc" +
      "e\030\005 \001(\014\"\246\002\n\014SearchResult\022\022\n\ntotal_hits\030\001" +
      " \001(\005\022\021\n\tmax_score\030\002 \001(\001\022\020\n\010max_took\030\003 \001(" +
      "\003\022\023\n\013max_took_id\030\004 \001(\r\022\035\n\006status\030\005 \001(\0132\r" +
      ".SearchStatus\022\013\n\003msg\030\006 \001(\t\022!\n\014result_ite" +
      "ms\030\007 \003(\0132\013.ResultItem\022\013\n\003pID\030\010 \001(\r\022+\n\007ex" +
      "plain\030\t \003(\0132\032.SearchResult.ExplainEntry\022" +
      "\017\n\007timeout\030\n \001(\010\032.\n\014ExplainEntry\022\013\n\003key\030" +
      "\001 \001(\r\022\r\n\005value\030\002 \001(\t:\0028\001\"\217\002\n\016SearchRespo" +
      "nse\022\033\n\004head\030\001 \001(\0132\r.ResponseHead\022\036\n\007resu" +
      "lts\030\002 \003(\0132\r.SearchResult\022\032\n\022online_log_m" +
      "essage\030\003 \001(\t\022\017\n\007timeout\030\004 \001(\010\022\021\n\tFlatByt" +
      "es\030\005 \001(\014\0229\n\016sort_field_map\030\006 \003(\0132!.Searc" +
      "hResponse.SortFieldMapEntry\022\020\n\010top_size\030" +
      "\007 \001(\005\0323\n\021SortFieldMapEntry\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\t:\0028\001\"N\n\014SearchStatus\022\r\n\005to" +
      "tal\030\001 \001(\005\022\016\n\006failed\030\002 \001(\005\022\022\n\nsuccessful\030" +
      "\003 \001(\005\022\013\n\003msg\030\004 \001(\t\"U\n\016MSearchRequest\022\032\n\004" +
      "head\030\001 \001(\0132\014.RequestHead\022\'\n\017search_reque" +
      "sts\030\002 \003(\0132\016.SearchRequest2\331\002\n\021RouterGRPC" +
      "Service\022\"\n\003Get\022\013.GetRequest\032\014.GetRespons" +
      "e\"\000\022\"\n\003Add\022\013.AddRequest\032\014.AddResponse\"\000\022" +
      "+\n\006Delete\022\016.DeleteRequest\032\017.DeleteRespon" +
      "se\"\000\022+\n\006Update\022\016.UpdateRequest\032\017.UpdateR" +
      "esponse\"\000\022+\n\006Search\022\016.SearchRequest\032\017.Se" +
      "archResponse\"\000\022%\n\004Bulk\022\014.BulkRequest\032\r.B" +
      "ulkResponse\"\000\022-\n\007MSearch\022\017.MSearchReques" +
      "t\032\017.SearchResponse\"\000\022\037\n\005Space\022\014.RequestH" +
      "ead\032\006.Table\"\000B\032\n\026com.vearch.grpc.entityP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          DataModel.getDescriptor(),
          Errors.getDescriptor(),
        });
    internal_static_RequestHead_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestHead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestHead_descriptor,
        new String[] { "TimeOutMs", "UserName", "Password", "DbName", "SpaceName", "ClientType", "Params", "Leader", });
    internal_static_RequestHead_ParamsEntry_descriptor =
      internal_static_RequestHead_descriptor.getNestedTypes().get(0);
    internal_static_RequestHead_ParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestHead_ParamsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_ResponseHead_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseHead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseHead_descriptor,
        new String[] { "Err", "Params", });
    internal_static_ResponseHead_ParamsEntry_descriptor =
      internal_static_ResponseHead_descriptor.getNestedTypes().get(0);
    internal_static_ResponseHead_ParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseHead_ParamsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetRequest_descriptor,
        new String[] { "Head", "PrimaryKeys", });
    internal_static_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteRequest_descriptor,
        new String[] { "Head", "PrimaryKeys", });
    internal_static_AddRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddRequest_descriptor,
        new String[] { "Head", "Doc", });
    internal_static_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateRequest_descriptor,
        new String[] { "Head", "Doc", });
    internal_static_BulkRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_BulkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BulkRequest_descriptor,
        new String[] { "Head", "Docs", });
    internal_static_ForceMergeRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ForceMergeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ForceMergeRequest_descriptor,
        new String[] { "Head", });
    internal_static_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetResponse_descriptor,
        new String[] { "Head", "Items", });
    internal_static_AddResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_AddResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddResponse_descriptor,
        new String[] { "Head", "PrimaryKey", });
    internal_static_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateResponse_descriptor,
        new String[] { "Head", });
    internal_static_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteResponse_descriptor,
        new String[] { "Head", "Items", });
    internal_static_BulkResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_BulkResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BulkResponse_descriptor,
        new String[] { "Head", "Items", });
    internal_static_ForceMergeResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ForceMergeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ForceMergeResponse_descriptor,
        new String[] { "Head", "Shards", });
    internal_static_DelByQueryeResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_DelByQueryeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DelByQueryeResponse_descriptor,
        new String[] { "Head", "DelNum", });
    internal_static_TermFilter_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_TermFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TermFilter_descriptor,
        new String[] { "Field", "Value", "IsUnion", });
    internal_static_RangeFilter_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_RangeFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RangeFilter_descriptor,
        new String[] { "Field", "LowerValue", "UpperValue", "IncludeLower", "IncludeUpper", });
    internal_static_SortField_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_SortField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SortField_descriptor,
        new String[] { "Field", "Type", });
    internal_static_VectorQuery_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_VectorQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VectorQuery_descriptor,
        new String[] { "Name", "Value", "MinScore", "MaxScore", "Boost", "HasBoost", });
    internal_static_RetrievalParameters_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_RetrievalParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RetrievalParameters_descriptor,
        new String[] { "MetricType", "Nprobe", });
    internal_static_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchRequest_descriptor,
        new String[] { "Head", "ReqNum", "TopN", "IsBruteSearch", "VecFields", "Fields", "RangeFilters", "TermFilters", "OnlineLogLevel", "RetrievalParams", "HasRank", "MultiVectorRank", "ParallelBasedOnQuery", "L2Sqrt", "IvfFlat", "IsVectorValue", "SortFieldMap", "SortFields", });
    internal_static_SearchRequest_SortFieldMapEntry_descriptor =
      internal_static_SearchRequest_descriptor.getNestedTypes().get(0);
    internal_static_SearchRequest_SortFieldMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchRequest_SortFieldMapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_ResultItem_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_ResultItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResultItem_descriptor,
        new String[] { "Score", "Fields", "Extra", "PKey", "Source", });
    internal_static_SearchResult_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_SearchResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchResult_descriptor,
        new String[] { "TotalHits", "MaxScore", "MaxTook", "MaxTookId", "Status", "Msg", "ResultItems", "PID", "Explain", "Timeout", });
    internal_static_SearchResult_ExplainEntry_descriptor =
      internal_static_SearchResult_descriptor.getNestedTypes().get(0);
    internal_static_SearchResult_ExplainEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchResult_ExplainEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchResponse_descriptor,
        new String[] { "Head", "Results", "OnlineLogMessage", "Timeout", "FlatBytes", "SortFieldMap", "TopSize", });
    internal_static_SearchResponse_SortFieldMapEntry_descriptor =
      internal_static_SearchResponse_descriptor.getNestedTypes().get(0);
    internal_static_SearchResponse_SortFieldMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchResponse_SortFieldMapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_SearchStatus_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_SearchStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchStatus_descriptor,
        new String[] { "Total", "Failed", "Successful", "Msg", });
    internal_static_MSearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_MSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MSearchRequest_descriptor,
        new String[] { "Head", "SearchRequests", });
    DataModel.getDescriptor();
    Errors.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
