// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router_grpc.proto

package com.vearch.grpc.entity;

/**
 * Protobuf type {@code SearchResponse}
 */
public final class SearchResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SearchResponse)
    SearchResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchResponse.newBuilder() to construct.
  private SearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchResponse() {
    results_ = java.util.Collections.emptyList();
    onlineLogMessage_ = "";
    flatBytes_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SearchResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SearchResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ResponseHead.Builder subBuilder = null;
            if (head_ != null) {
              subBuilder = head_.toBuilder();
            }
            head_ = input.readMessage(ResponseHead.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(head_);
              head_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              results_ = new java.util.ArrayList<SearchResult>();
              mutable_bitField0_ |= 0x00000001;
            }
            results_.add(
                input.readMessage(SearchResult.parser(), extensionRegistry));
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            onlineLogMessage_ = s;
            break;
          }
          case 32: {

            timeout_ = input.readBool();
            break;
          }
          case 42: {

            flatBytes_ = input.readBytes();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              sortFieldMap_ = com.google.protobuf.MapField.newMapField(
                  SortFieldMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<String, String>
            sortFieldMap__ = input.readMessage(
                SortFieldMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            sortFieldMap_.getMutableMap().put(
                sortFieldMap__.getKey(), sortFieldMap__.getValue());
            break;
          }
          case 56: {

            topSize_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        results_ = java.util.Collections.unmodifiableList(results_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RouterGrpc.internal_static_SearchResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetSortFieldMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RouterGrpc.internal_static_SearchResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SearchResponse.class, SearchResponse.Builder.class);
  }

  public static final int HEAD_FIELD_NUMBER = 1;
  private ResponseHead head_;
  /**
   * <code>.ResponseHead head = 1;</code>
   * @return Whether the head field is set.
   */
  @Override
  public boolean hasHead() {
    return head_ != null;
  }
  /**
   * <code>.ResponseHead head = 1;</code>
   * @return The head.
   */
  @Override
  public ResponseHead getHead() {
    return head_ == null ? ResponseHead.getDefaultInstance() : head_;
  }
  /**
   * <code>.ResponseHead head = 1;</code>
   */
  @Override
  public ResponseHeadOrBuilder getHeadOrBuilder() {
    return getHead();
  }

  public static final int RESULTS_FIELD_NUMBER = 2;
  private java.util.List<SearchResult> results_;
  /**
   * <code>repeated .SearchResult results = 2;</code>
   */
  @Override
  public java.util.List<SearchResult> getResultsList() {
    return results_;
  }
  /**
   * <code>repeated .SearchResult results = 2;</code>
   */
  @Override
  public java.util.List<? extends SearchResultOrBuilder>
      getResultsOrBuilderList() {
    return results_;
  }
  /**
   * <code>repeated .SearchResult results = 2;</code>
   */
  @Override
  public int getResultsCount() {
    return results_.size();
  }
  /**
   * <code>repeated .SearchResult results = 2;</code>
   */
  @Override
  public SearchResult getResults(int index) {
    return results_.get(index);
  }
  /**
   * <code>repeated .SearchResult results = 2;</code>
   */
  @Override
  public SearchResultOrBuilder getResultsOrBuilder(
      int index) {
    return results_.get(index);
  }

  public static final int ONLINE_LOG_MESSAGE_FIELD_NUMBER = 3;
  private volatile Object onlineLogMessage_;
  /**
   * <code>string online_log_message = 3;</code>
   * @return The onlineLogMessage.
   */
  @Override
  public String getOnlineLogMessage() {
    Object ref = onlineLogMessage_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      onlineLogMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string online_log_message = 3;</code>
   * @return The bytes for onlineLogMessage.
   */
  @Override
  public com.google.protobuf.ByteString
      getOnlineLogMessageBytes() {
    Object ref = onlineLogMessage_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      onlineLogMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEOUT_FIELD_NUMBER = 4;
  private boolean timeout_;
  /**
   * <code>bool timeout = 4;</code>
   * @return The timeout.
   */
  @Override
  public boolean getTimeout() {
    return timeout_;
  }

  public static final int FLATBYTES_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString flatBytes_;
  /**
   * <code>bytes FlatBytes = 5;</code>
   * @return The flatBytes.
   */
  @Override
  public com.google.protobuf.ByteString getFlatBytes() {
    return flatBytes_;
  }

  public static final int SORT_FIELD_MAP_FIELD_NUMBER = 6;
  private static final class SortFieldMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                RouterGrpc.internal_static_SearchResponse_SortFieldMapEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      String, String> sortFieldMap_;
  private com.google.protobuf.MapField<String, String>
  internalGetSortFieldMap() {
    if (sortFieldMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SortFieldMapDefaultEntryHolder.defaultEntry);
    }
    return sortFieldMap_;
  }

  public int getSortFieldMapCount() {
    return internalGetSortFieldMap().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; sort_field_map = 6;</code>
   */

  @Override
  public boolean containsSortFieldMap(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    return internalGetSortFieldMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSortFieldMapMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, String> getSortFieldMap() {
    return getSortFieldMapMap();
  }
  /**
   * <code>map&lt;string, string&gt; sort_field_map = 6;</code>
   */
  @Override

  public java.util.Map<String, String> getSortFieldMapMap() {
    return internalGetSortFieldMap().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; sort_field_map = 6;</code>
   */
  @Override

  public String getSortFieldMapOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, String> map =
        internalGetSortFieldMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; sort_field_map = 6;</code>
   */
  @Override

  public String getSortFieldMapOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, String> map =
        internalGetSortFieldMap().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TOP_SIZE_FIELD_NUMBER = 7;
  private int topSize_;
  /**
   * <code>int32 top_size = 7;</code>
   * @return The topSize.
   */
  @Override
  public int getTopSize() {
    return topSize_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (head_ != null) {
      output.writeMessage(1, getHead());
    }
    for (int i = 0; i < results_.size(); i++) {
      output.writeMessage(2, results_.get(i));
    }
    if (!getOnlineLogMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, onlineLogMessage_);
    }
    if (timeout_ != false) {
      output.writeBool(4, timeout_);
    }
    if (!flatBytes_.isEmpty()) {
      output.writeBytes(5, flatBytes_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetSortFieldMap(),
        SortFieldMapDefaultEntryHolder.defaultEntry,
        6);
    if (topSize_ != 0) {
      output.writeInt32(7, topSize_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (head_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHead());
    }
    for (int i = 0; i < results_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, results_.get(i));
    }
    if (!getOnlineLogMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, onlineLogMessage_);
    }
    if (timeout_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, timeout_);
    }
    if (!flatBytes_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, flatBytes_);
    }
    for (java.util.Map.Entry<String, String> entry
         : internalGetSortFieldMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      sortFieldMap__ = SortFieldMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, sortFieldMap__);
    }
    if (topSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, topSize_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SearchResponse)) {
      return super.equals(obj);
    }
    SearchResponse other = (SearchResponse) obj;

    if (hasHead() != other.hasHead()) return false;
    if (hasHead()) {
      if (!getHead()
          .equals(other.getHead())) return false;
    }
    if (!getResultsList()
        .equals(other.getResultsList())) return false;
    if (!getOnlineLogMessage()
        .equals(other.getOnlineLogMessage())) return false;
    if (getTimeout()
        != other.getTimeout()) return false;
    if (!getFlatBytes()
        .equals(other.getFlatBytes())) return false;
    if (!internalGetSortFieldMap().equals(
        other.internalGetSortFieldMap())) return false;
    if (getTopSize()
        != other.getTopSize()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHead()) {
      hash = (37 * hash) + HEAD_FIELD_NUMBER;
      hash = (53 * hash) + getHead().hashCode();
    }
    if (getResultsCount() > 0) {
      hash = (37 * hash) + RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getResultsList().hashCode();
    }
    hash = (37 * hash) + ONLINE_LOG_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getOnlineLogMessage().hashCode();
    hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTimeout());
    hash = (37 * hash) + FLATBYTES_FIELD_NUMBER;
    hash = (53 * hash) + getFlatBytes().hashCode();
    if (!internalGetSortFieldMap().getMap().isEmpty()) {
      hash = (37 * hash) + SORT_FIELD_MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSortFieldMap().hashCode();
    }
    hash = (37 * hash) + TOP_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getTopSize();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SearchResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SearchResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SearchResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SearchResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SearchResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SearchResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SearchResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SearchResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SearchResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SearchResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SearchResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SearchResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SearchResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SearchResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SearchResponse)
      SearchResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RouterGrpc.internal_static_SearchResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetSortFieldMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableSortFieldMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RouterGrpc.internal_static_SearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SearchResponse.class, SearchResponse.Builder.class);
    }

    // Construct using com.vearch.grpc.entity.SearchResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResultsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (headBuilder_ == null) {
        head_ = null;
      } else {
        head_ = null;
        headBuilder_ = null;
      }
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        resultsBuilder_.clear();
      }
      onlineLogMessage_ = "";

      timeout_ = false;

      flatBytes_ = com.google.protobuf.ByteString.EMPTY;

      internalGetMutableSortFieldMap().clear();
      topSize_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RouterGrpc.internal_static_SearchResponse_descriptor;
    }

    @Override
    public SearchResponse getDefaultInstanceForType() {
      return SearchResponse.getDefaultInstance();
    }

    @Override
    public SearchResponse build() {
      SearchResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SearchResponse buildPartial() {
      SearchResponse result = new SearchResponse(this);
      int from_bitField0_ = bitField0_;
      if (headBuilder_ == null) {
        result.head_ = head_;
      } else {
        result.head_ = headBuilder_.build();
      }
      if (resultsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          results_ = java.util.Collections.unmodifiableList(results_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.results_ = results_;
      } else {
        result.results_ = resultsBuilder_.build();
      }
      result.onlineLogMessage_ = onlineLogMessage_;
      result.timeout_ = timeout_;
      result.flatBytes_ = flatBytes_;
      result.sortFieldMap_ = internalGetSortFieldMap();
      result.sortFieldMap_.makeImmutable();
      result.topSize_ = topSize_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SearchResponse) {
        return mergeFrom((SearchResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SearchResponse other) {
      if (other == SearchResponse.getDefaultInstance()) return this;
      if (other.hasHead()) {
        mergeHead(other.getHead());
      }
      if (resultsBuilder_ == null) {
        if (!other.results_.isEmpty()) {
          if (results_.isEmpty()) {
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultsIsMutable();
            results_.addAll(other.results_);
          }
          onChanged();
        }
      } else {
        if (!other.results_.isEmpty()) {
          if (resultsBuilder_.isEmpty()) {
            resultsBuilder_.dispose();
            resultsBuilder_ = null;
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000001);
            resultsBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResultsFieldBuilder() : null;
          } else {
            resultsBuilder_.addAllMessages(other.results_);
          }
        }
      }
      if (!other.getOnlineLogMessage().isEmpty()) {
        onlineLogMessage_ = other.onlineLogMessage_;
        onChanged();
      }
      if (other.getTimeout() != false) {
        setTimeout(other.getTimeout());
      }
      if (other.getFlatBytes() != com.google.protobuf.ByteString.EMPTY) {
        setFlatBytes(other.getFlatBytes());
      }
      internalGetMutableSortFieldMap().mergeFrom(
          other.internalGetSortFieldMap());
      if (other.getTopSize() != 0) {
        setTopSize(other.getTopSize());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SearchResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SearchResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private ResponseHead head_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ResponseHead, ResponseHead.Builder, ResponseHeadOrBuilder> headBuilder_;
    /**
     * <code>.ResponseHead head = 1;</code>
     * @return Whether the head field is set.
     */
    public boolean hasHead() {
      return headBuilder_ != null || head_ != null;
    }
    /**
     * <code>.ResponseHead head = 1;</code>
     * @return The head.
     */
    public ResponseHead getHead() {
      if (headBuilder_ == null) {
        return head_ == null ? ResponseHead.getDefaultInstance() : head_;
      } else {
        return headBuilder_.getMessage();
      }
    }
    /**
     * <code>.ResponseHead head = 1;</code>
     */
    public Builder setHead(ResponseHead value) {
      if (headBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        head_ = value;
        onChanged();
      } else {
        headBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ResponseHead head = 1;</code>
     */
    public Builder setHead(
        ResponseHead.Builder builderForValue) {
      if (headBuilder_ == null) {
        head_ = builderForValue.build();
        onChanged();
      } else {
        headBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ResponseHead head = 1;</code>
     */
    public Builder mergeHead(ResponseHead value) {
      if (headBuilder_ == null) {
        if (head_ != null) {
          head_ =
            ResponseHead.newBuilder(head_).mergeFrom(value).buildPartial();
        } else {
          head_ = value;
        }
        onChanged();
      } else {
        headBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ResponseHead head = 1;</code>
     */
    public Builder clearHead() {
      if (headBuilder_ == null) {
        head_ = null;
        onChanged();
      } else {
        head_ = null;
        headBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ResponseHead head = 1;</code>
     */
    public ResponseHead.Builder getHeadBuilder() {

      onChanged();
      return getHeadFieldBuilder().getBuilder();
    }
    /**
     * <code>.ResponseHead head = 1;</code>
     */
    public ResponseHeadOrBuilder getHeadOrBuilder() {
      if (headBuilder_ != null) {
        return headBuilder_.getMessageOrBuilder();
      } else {
        return head_ == null ?
            ResponseHead.getDefaultInstance() : head_;
      }
    }
    /**
     * <code>.ResponseHead head = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ResponseHead, ResponseHead.Builder, ResponseHeadOrBuilder>
        getHeadFieldBuilder() {
      if (headBuilder_ == null) {
        headBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ResponseHead, ResponseHead.Builder, ResponseHeadOrBuilder>(
                getHead(),
                getParentForChildren(),
                isClean());
        head_ = null;
      }
      return headBuilder_;
    }

    private java.util.List<SearchResult> results_ =
      java.util.Collections.emptyList();
    private void ensureResultsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        results_ = new java.util.ArrayList<SearchResult>(results_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        SearchResult, SearchResult.Builder, SearchResultOrBuilder> resultsBuilder_;

    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public java.util.List<SearchResult> getResultsList() {
      if (resultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(results_);
      } else {
        return resultsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public int getResultsCount() {
      if (resultsBuilder_ == null) {
        return results_.size();
      } else {
        return resultsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public SearchResult getResults(int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);
      } else {
        return resultsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public Builder setResults(
        int index, SearchResult value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.set(index, value);
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public Builder setResults(
        int index, SearchResult.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public Builder addResults(SearchResult value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public Builder addResults(
        int index, SearchResult value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(index, value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public Builder addResults(
        SearchResult.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public Builder addResults(
        int index, SearchResult.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public Builder addAllResults(
        Iterable<? extends SearchResult> values) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, results_);
        onChanged();
      } else {
        resultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public Builder clearResults() {
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public Builder removeResults(int index) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.remove(index);
        onChanged();
      } else {
        resultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public SearchResult.Builder getResultsBuilder(
        int index) {
      return getResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public SearchResultOrBuilder getResultsOrBuilder(
        int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);  } else {
        return resultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public java.util.List<? extends SearchResultOrBuilder>
         getResultsOrBuilderList() {
      if (resultsBuilder_ != null) {
        return resultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(results_);
      }
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public SearchResult.Builder addResultsBuilder() {
      return getResultsFieldBuilder().addBuilder(
          SearchResult.getDefaultInstance());
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public SearchResult.Builder addResultsBuilder(
        int index) {
      return getResultsFieldBuilder().addBuilder(
          index, SearchResult.getDefaultInstance());
    }
    /**
     * <code>repeated .SearchResult results = 2;</code>
     */
    public java.util.List<SearchResult.Builder>
         getResultsBuilderList() {
      return getResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        SearchResult, SearchResult.Builder, SearchResultOrBuilder>
        getResultsFieldBuilder() {
      if (resultsBuilder_ == null) {
        resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            SearchResult, SearchResult.Builder, SearchResultOrBuilder>(
                results_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        results_ = null;
      }
      return resultsBuilder_;
    }

    private Object onlineLogMessage_ = "";
    /**
     * <code>string online_log_message = 3;</code>
     * @return The onlineLogMessage.
     */
    public String getOnlineLogMessage() {
      Object ref = onlineLogMessage_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        onlineLogMessage_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string online_log_message = 3;</code>
     * @return The bytes for onlineLogMessage.
     */
    public com.google.protobuf.ByteString
        getOnlineLogMessageBytes() {
      Object ref = onlineLogMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        onlineLogMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string online_log_message = 3;</code>
     * @param value The onlineLogMessage to set.
     * @return This builder for chaining.
     */
    public Builder setOnlineLogMessage(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      onlineLogMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string online_log_message = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOnlineLogMessage() {

      onlineLogMessage_ = getDefaultInstance().getOnlineLogMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string online_log_message = 3;</code>
     * @param value The bytes for onlineLogMessage to set.
     * @return This builder for chaining.
     */
    public Builder setOnlineLogMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      onlineLogMessage_ = value;
      onChanged();
      return this;
    }

    private boolean timeout_ ;
    /**
     * <code>bool timeout = 4;</code>
     * @return The timeout.
     */
    @Override
    public boolean getTimeout() {
      return timeout_;
    }
    /**
     * <code>bool timeout = 4;</code>
     * @param value The timeout to set.
     * @return This builder for chaining.
     */
    public Builder setTimeout(boolean value) {

      timeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool timeout = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeout() {

      timeout_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString flatBytes_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes FlatBytes = 5;</code>
     * @return The flatBytes.
     */
    @Override
    public com.google.protobuf.ByteString getFlatBytes() {
      return flatBytes_;
    }
    /**
     * <code>bytes FlatBytes = 5;</code>
     * @param value The flatBytes to set.
     * @return This builder for chaining.
     */
    public Builder setFlatBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      flatBytes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes FlatBytes = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlatBytes() {

      flatBytes_ = getDefaultInstance().getFlatBytes();
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        String, String> sortFieldMap_;
    private com.google.protobuf.MapField<String, String>
    internalGetSortFieldMap() {
      if (sortFieldMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SortFieldMapDefaultEntryHolder.defaultEntry);
      }
      return sortFieldMap_;
    }
    private com.google.protobuf.MapField<String, String>
    internalGetMutableSortFieldMap() {
      onChanged();;
      if (sortFieldMap_ == null) {
        sortFieldMap_ = com.google.protobuf.MapField.newMapField(
            SortFieldMapDefaultEntryHolder.defaultEntry);
      }
      if (!sortFieldMap_.isMutable()) {
        sortFieldMap_ = sortFieldMap_.copy();
      }
      return sortFieldMap_;
    }

    public int getSortFieldMapCount() {
      return internalGetSortFieldMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; sort_field_map = 6;</code>
     */

    @Override
    public boolean containsSortFieldMap(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetSortFieldMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSortFieldMapMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getSortFieldMap() {
      return getSortFieldMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; sort_field_map = 6;</code>
     */
    @Override

    public java.util.Map<String, String> getSortFieldMapMap() {
      return internalGetSortFieldMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; sort_field_map = 6;</code>
     */
    @Override

    public String getSortFieldMapOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetSortFieldMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; sort_field_map = 6;</code>
     */
    @Override

    public String getSortFieldMapOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetSortFieldMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearSortFieldMap() {
      internalGetMutableSortFieldMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; sort_field_map = 6;</code>
     */

    public Builder removeSortFieldMap(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      internalGetMutableSortFieldMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableSortFieldMap() {
      return internalGetMutableSortFieldMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; sort_field_map = 6;</code>
     */
    public Builder putSortFieldMap(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException(); }
      if (value == null) { throw new NullPointerException(); }
      internalGetMutableSortFieldMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; sort_field_map = 6;</code>
     */

    public Builder putAllSortFieldMap(
        java.util.Map<String, String> values) {
      internalGetMutableSortFieldMap().getMutableMap()
          .putAll(values);
      return this;
    }

    private int topSize_ ;
    /**
     * <code>int32 top_size = 7;</code>
     * @return The topSize.
     */
    @Override
    public int getTopSize() {
      return topSize_;
    }
    /**
     * <code>int32 top_size = 7;</code>
     * @param value The topSize to set.
     * @return This builder for chaining.
     */
    public Builder setTopSize(int value) {

      topSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 top_size = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopSize() {

      topSize_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SearchResponse)
  }

  // @@protoc_insertion_point(class_scope:SearchResponse)
  private static final SearchResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SearchResponse();
  }

  public static SearchResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchResponse>
      PARSER = new com.google.protobuf.AbstractParser<SearchResponse>() {
    @Override
    public SearchResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SearchResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SearchResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SearchResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public SearchResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

