// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router_grpc.proto

package com.vearch.grpc.entity;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.RequestHead head = 1;</code>
   * @return Whether the head field is set.
   */
  boolean hasHead();
  /**
   * <code>.RequestHead head = 1;</code>
   * @return The head.
   */
  RequestHead getHead();
  /**
   * <code>.RequestHead head = 1;</code>
   */
  RequestHeadOrBuilder getHeadOrBuilder();

  /**
   * <code>int32 req_num = 2;</code>
   * @return The reqNum.
   */
  int getReqNum();

  /**
   * <code>int32 topN = 3;</code>
   * @return The topN.
   */
  int getTopN();

  /**
   * <code>int32 is_brute_search = 4;</code>
   * @return The isBruteSearch.
   */
  int getIsBruteSearch();

  /**
   * <code>repeated .VectorQuery vec_fields = 5;</code>
   */
  java.util.List<VectorQuery>
      getVecFieldsList();
  /**
   * <code>repeated .VectorQuery vec_fields = 5;</code>
   */
  VectorQuery getVecFields(int index);
  /**
   * <code>repeated .VectorQuery vec_fields = 5;</code>
   */
  int getVecFieldsCount();
  /**
   * <code>repeated .VectorQuery vec_fields = 5;</code>
   */
  java.util.List<? extends VectorQueryOrBuilder>
      getVecFieldsOrBuilderList();
  /**
   * <code>repeated .VectorQuery vec_fields = 5;</code>
   */
  VectorQueryOrBuilder getVecFieldsOrBuilder(
          int index);

  /**
   * <code>repeated string fields = 6;</code>
   * @return A list containing the fields.
   */
  java.util.List<String>
      getFieldsList();
  /**
   * <code>repeated string fields = 6;</code>
   * @return The count of fields.
   */
  int getFieldsCount();
  /**
   * <code>repeated string fields = 6;</code>
   * @param index The index of the element to return.
   * @return The fields at the given index.
   */
  String getFields(int index);
  /**
   * <code>repeated string fields = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the fields at the given index.
   */
  com.google.protobuf.ByteString
      getFieldsBytes(int index);

  /**
   * <code>repeated .RangeFilter range_filters = 7;</code>
   */
  java.util.List<RangeFilter>
      getRangeFiltersList();
  /**
   * <code>repeated .RangeFilter range_filters = 7;</code>
   */
  RangeFilter getRangeFilters(int index);
  /**
   * <code>repeated .RangeFilter range_filters = 7;</code>
   */
  int getRangeFiltersCount();
  /**
   * <code>repeated .RangeFilter range_filters = 7;</code>
   */
  java.util.List<? extends RangeFilterOrBuilder>
      getRangeFiltersOrBuilderList();
  /**
   * <code>repeated .RangeFilter range_filters = 7;</code>
   */
  RangeFilterOrBuilder getRangeFiltersOrBuilder(
          int index);

  /**
   * <code>repeated .TermFilter term_filters = 8;</code>
   */
  java.util.List<TermFilter>
      getTermFiltersList();
  /**
   * <code>repeated .TermFilter term_filters = 8;</code>
   */
  TermFilter getTermFilters(int index);
  /**
   * <code>repeated .TermFilter term_filters = 8;</code>
   */
  int getTermFiltersCount();
  /**
   * <code>repeated .TermFilter term_filters = 8;</code>
   */
  java.util.List<? extends TermFilterOrBuilder>
      getTermFiltersOrBuilderList();
  /**
   * <code>repeated .TermFilter term_filters = 8;</code>
   */
  TermFilterOrBuilder getTermFiltersOrBuilder(
          int index);

  /**
   * <code>string online_log_level = 9;</code>
   * @return The onlineLogLevel.
   */
  String getOnlineLogLevel();
  /**
   * <code>string online_log_level = 9;</code>
   * @return The bytes for onlineLogLevel.
   */
  com.google.protobuf.ByteString
      getOnlineLogLevelBytes();

  /**
   * <code>string retrieval_params = 10;</code>
   * @return The retrievalParams.
   */
  String getRetrievalParams();
  /**
   * <code>string retrieval_params = 10;</code>
   * @return The bytes for retrievalParams.
   */
  com.google.protobuf.ByteString
      getRetrievalParamsBytes();

  /**
   * <code>bool has_rank = 11;</code>
   * @return The hasRank.
   */
  boolean getHasRank();

  /**
   * <code>int32 multi_vector_rank = 12;</code>
   * @return The multiVectorRank.
   */
  int getMultiVectorRank();

  /**
   * <code>bool parallel_based_on_query = 13;</code>
   * @return The parallelBasedOnQuery.
   */
  boolean getParallelBasedOnQuery();

  /**
   * <code>bool l2_sqrt = 14;</code>
   * @return The l2Sqrt.
   */
  boolean getL2Sqrt();

  /**
   * <code>bool ivf_flat = 15;</code>
   * @return The ivfFlat.
   */
  boolean getIvfFlat();

  /**
   * <code>bool is_vector_value = 16;</code>
   * @return The isVectorValue.
   */
  boolean getIsVectorValue();

  /**
   * <code>map&lt;string, string&gt; sort_field_map = 17;</code>
   */
  int getSortFieldMapCount();
  /**
   * <code>map&lt;string, string&gt; sort_field_map = 17;</code>
   */
  boolean containsSortFieldMap(
          String key);
  /**
   * Use {@link #getSortFieldMapMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getSortFieldMap();
  /**
   * <code>map&lt;string, string&gt; sort_field_map = 17;</code>
   */
  java.util.Map<String, String>
  getSortFieldMapMap();
  /**
   * <code>map&lt;string, string&gt; sort_field_map = 17;</code>
   */

  String getSortFieldMapOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; sort_field_map = 17;</code>
   */

  String getSortFieldMapOrThrow(
          String key);

  /**
   * <code>repeated .SortField sort_fields = 18;</code>
   */
  java.util.List<SortField>
      getSortFieldsList();
  /**
   * <code>repeated .SortField sort_fields = 18;</code>
   */
  SortField getSortFields(int index);
  /**
   * <code>repeated .SortField sort_fields = 18;</code>
   */
  int getSortFieldsCount();
  /**
   * <code>repeated .SortField sort_fields = 18;</code>
   */
  java.util.List<? extends SortFieldOrBuilder>
      getSortFieldsOrBuilderList();
  /**
   * <code>repeated .SortField sort_fields = 18;</code>
   */
  SortFieldOrBuilder getSortFieldsOrBuilder(
          int index);
}
