// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router_grpc.proto

package com.vearch.grpc.entity;

public interface SearchResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 total_hits = 1;</code>
   * @return The totalHits.
   */
  int getTotalHits();

  /**
   * <code>double max_score = 2;</code>
   * @return The maxScore.
   */
  double getMaxScore();

  /**
   * <code>int64 max_took = 3;</code>
   * @return The maxTook.
   */
  long getMaxTook();

  /**
   * <code>uint32 max_took_id = 4;</code>
   * @return The maxTookId.
   */
  int getMaxTookId();

  /**
   * <code>.SearchStatus status = 5;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.SearchStatus status = 5;</code>
   * @return The status.
   */
  SearchStatus getStatus();
  /**
   * <code>.SearchStatus status = 5;</code>
   */
  SearchStatusOrBuilder getStatusOrBuilder();

  /**
   * <code>string msg = 6;</code>
   * @return The msg.
   */
  String getMsg();
  /**
   * <code>string msg = 6;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>repeated .ResultItem result_items = 7;</code>
   */
  java.util.List<ResultItem>
      getResultItemsList();
  /**
   * <code>repeated .ResultItem result_items = 7;</code>
   */
  ResultItem getResultItems(int index);
  /**
   * <code>repeated .ResultItem result_items = 7;</code>
   */
  int getResultItemsCount();
  /**
   * <code>repeated .ResultItem result_items = 7;</code>
   */
  java.util.List<? extends ResultItemOrBuilder>
      getResultItemsOrBuilderList();
  /**
   * <code>repeated .ResultItem result_items = 7;</code>
   */
  ResultItemOrBuilder getResultItemsOrBuilder(
          int index);

  /**
   * <code>uint32 pID = 8;</code>
   * @return The pID.
   */
  int getPID();

  /**
   * <code>map&lt;uint32, string&gt; explain = 9;</code>
   */
  int getExplainCount();
  /**
   * <code>map&lt;uint32, string&gt; explain = 9;</code>
   */
  boolean containsExplain(
          int key);
  /**
   * Use {@link #getExplainMap()} instead.
   */
  @Deprecated
  java.util.Map<Integer, String>
  getExplain();
  /**
   * <code>map&lt;uint32, string&gt; explain = 9;</code>
   */
  java.util.Map<Integer, String>
  getExplainMap();
  /**
   * <code>map&lt;uint32, string&gt; explain = 9;</code>
   */

  String getExplainOrDefault(
          int key,
          String defaultValue);
  /**
   * <code>map&lt;uint32, string&gt; explain = 9;</code>
   */

  String getExplainOrThrow(
          int key);

  /**
   * <code>bool timeout = 10;</code>
   * @return The timeout.
   */
  boolean getTimeout();
}
