// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_model.proto

package com.vearch.grpc.entity;

public interface TableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Table)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.TableMetaInfo table_meta_info = 2;</code>
   * @return Whether the tableMetaInfo field is set.
   */
  boolean hasTableMetaInfo();
  /**
   * <code>.TableMetaInfo table_meta_info = 2;</code>
   * @return The tableMetaInfo.
   */
  TableMetaInfo getTableMetaInfo();
  /**
   * <code>.TableMetaInfo table_meta_info = 2;</code>
   */
  TableMetaInfoOrBuilder getTableMetaInfoOrBuilder();

  /**
   * <code>int32 start_indexing_size = 3;</code>
   * @return The startIndexingSize.
   */
  int getStartIndexingSize();

  /**
   * <code>.Model model = 4;</code>
   * @return Whether the model field is set.
   */
  boolean hasModel();
  /**
   * <code>.Model model = 4;</code>
   * @return The model.
   */
  Model getModel();
  /**
   * <code>.Model model = 4;</code>
   */
  ModelOrBuilder getModelOrBuilder();

  /**
   * <code>int64 total_docs_size = 5;</code>
   * @return The totalDocsSize.
   */
  long getTotalDocsSize();
}
