// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router_grpc.proto

package com.vearch.grpc.entity;

public interface UpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ResponseHead head = 1;</code>
   * @return Whether the head field is set.
   */
  boolean hasHead();
  /**
   * <code>.ResponseHead head = 1;</code>
   * @return The head.
   */
  ResponseHead getHead();
  /**
   * <code>.ResponseHead head = 1;</code>
   */
  ResponseHeadOrBuilder getHeadOrBuilder();
}
