// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_model.proto

package com.vearch.grpc.entity;

public interface VectorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Vector)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated float feature = 1 [packed = true];</code>
   * @return A list containing the feature.
   */
  java.util.List<Float> getFeatureList();
  /**
   * <code>repeated float feature = 1 [packed = true];</code>
   * @return The count of feature.
   */
  int getFeatureCount();
  /**
   * <code>repeated float feature = 1 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The feature at the given index.
   */
  float getFeature(int index);

  /**
   * <code>string source = 2;</code>
   * @return The source.
   */
  String getSource();
  /**
   * <code>string source = 2;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();
}
