// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_model.proto

package com.vearch.grpc.entity;

/**
 * Protobuf type {@code VectorMetaInfo}
 */
public final class VectorMetaInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:VectorMetaInfo)
    VectorMetaInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VectorMetaInfo.newBuilder() to construct.
  private VectorMetaInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VectorMetaInfo() {
    valueType_ = 0;
    storeType_ = 0;
    storeParam_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new VectorMetaInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VectorMetaInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            dimension_ = input.readInt32();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            valueType_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            storeType_ = rawValue;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            storeParam_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DataModel.internal_static_VectorMetaInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DataModel.internal_static_VectorMetaInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            VectorMetaInfo.class, VectorMetaInfo.Builder.class);
  }

  /**
   * Protobuf enum {@code VectorMetaInfo.ValueType}
   */
  public enum ValueType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FLOAT = 0;</code>
     */
    FLOAT(0),
    /**
     * <pre>
     * binary
     * </pre>
     *
     * <code>UINT8 = 1;</code>
     */
    UINT8(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FLOAT = 0;</code>
     */
    public static final int FLOAT_VALUE = 0;
    /**
     * <pre>
     * binary
     * </pre>
     *
     * <code>UINT8 = 1;</code>
     */
    public static final int UINT8_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ValueType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ValueType forNumber(int value) {
      switch (value) {
        case 0: return FLOAT;
        case 1: return UINT8;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ValueType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ValueType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ValueType>() {
            public ValueType findValueByNumber(int number) {
              return ValueType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return VectorMetaInfo.getDescriptor().getEnumTypes().get(0);
    }

    private static final ValueType[] VALUES = values();

    public static ValueType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ValueType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:VectorMetaInfo.ValueType)
  }

  /**
   * Protobuf enum {@code VectorMetaInfo.StoreType}
   */
  public enum StoreType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MMAP = 0;</code>
     */
    MMAP(0),
    /**
     * <code>ROCKSDB = 1;</code>
     */
    ROCKSDB(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MMAP = 0;</code>
     */
    public static final int MMAP_VALUE = 0;
    /**
     * <code>ROCKSDB = 1;</code>
     */
    public static final int ROCKSDB_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static StoreType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static StoreType forNumber(int value) {
      switch (value) {
        case 0: return MMAP;
        case 1: return ROCKSDB;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StoreType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StoreType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StoreType>() {
            public StoreType findValueByNumber(int number) {
              return StoreType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return VectorMetaInfo.getDescriptor().getEnumTypes().get(1);
    }

    private static final StoreType[] VALUES = values();

    public static StoreType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StoreType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:VectorMetaInfo.StoreType)
  }

  public static final int DIMENSION_FIELD_NUMBER = 1;
  private int dimension_;
  /**
   * <code>int32 dimension = 1;</code>
   * @return The dimension.
   */
  @Override
  public int getDimension() {
    return dimension_;
  }

  public static final int VALUE_TYPE_FIELD_NUMBER = 2;
  private int valueType_;
  /**
   * <code>.VectorMetaInfo.ValueType value_type = 2;</code>
   * @return The enum numeric value on the wire for valueType.
   */
  @Override public int getValueTypeValue() {
    return valueType_;
  }
  /**
   * <code>.VectorMetaInfo.ValueType value_type = 2;</code>
   * @return The valueType.
   */
  @Override public VectorMetaInfo.ValueType getValueType() {
    @SuppressWarnings("deprecation")
    VectorMetaInfo.ValueType result = VectorMetaInfo.ValueType.valueOf(valueType_);
    return result == null ? VectorMetaInfo.ValueType.UNRECOGNIZED : result;
  }

  public static final int STORE_TYPE_FIELD_NUMBER = 3;
  private int storeType_;
  /**
   * <code>.VectorMetaInfo.StoreType store_type = 3;</code>
   * @return The enum numeric value on the wire for storeType.
   */
  @Override public int getStoreTypeValue() {
    return storeType_;
  }
  /**
   * <code>.VectorMetaInfo.StoreType store_type = 3;</code>
   * @return The storeType.
   */
  @Override public VectorMetaInfo.StoreType getStoreType() {
    @SuppressWarnings("deprecation")
    VectorMetaInfo.StoreType result = VectorMetaInfo.StoreType.valueOf(storeType_);
    return result == null ? VectorMetaInfo.StoreType.UNRECOGNIZED : result;
  }

  public static final int STORE_PARAM_FIELD_NUMBER = 4;
  private volatile Object storeParam_;
  /**
   * <code>string store_param = 4;</code>
   * @return The storeParam.
   */
  @Override
  public String getStoreParam() {
    Object ref = storeParam_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      storeParam_ = s;
      return s;
    }
  }
  /**
   * <code>string store_param = 4;</code>
   * @return The bytes for storeParam.
   */
  @Override
  public com.google.protobuf.ByteString
      getStoreParamBytes() {
    Object ref = storeParam_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      storeParam_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dimension_ != 0) {
      output.writeInt32(1, dimension_);
    }
    if (valueType_ != VectorMetaInfo.ValueType.FLOAT.getNumber()) {
      output.writeEnum(2, valueType_);
    }
    if (storeType_ != VectorMetaInfo.StoreType.MMAP.getNumber()) {
      output.writeEnum(3, storeType_);
    }
    if (!getStoreParamBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, storeParam_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dimension_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, dimension_);
    }
    if (valueType_ != VectorMetaInfo.ValueType.FLOAT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, valueType_);
    }
    if (storeType_ != VectorMetaInfo.StoreType.MMAP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, storeType_);
    }
    if (!getStoreParamBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, storeParam_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof VectorMetaInfo)) {
      return super.equals(obj);
    }
    VectorMetaInfo other = (VectorMetaInfo) obj;

    if (getDimension()
        != other.getDimension()) return false;
    if (valueType_ != other.valueType_) return false;
    if (storeType_ != other.storeType_) return false;
    if (!getStoreParam()
        .equals(other.getStoreParam())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DIMENSION_FIELD_NUMBER;
    hash = (53 * hash) + getDimension();
    hash = (37 * hash) + VALUE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + valueType_;
    hash = (37 * hash) + STORE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + storeType_;
    hash = (37 * hash) + STORE_PARAM_FIELD_NUMBER;
    hash = (53 * hash) + getStoreParam().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static VectorMetaInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VectorMetaInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VectorMetaInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VectorMetaInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VectorMetaInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VectorMetaInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VectorMetaInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VectorMetaInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static VectorMetaInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static VectorMetaInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static VectorMetaInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VectorMetaInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(VectorMetaInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VectorMetaInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VectorMetaInfo)
      VectorMetaInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataModel.internal_static_VectorMetaInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataModel.internal_static_VectorMetaInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VectorMetaInfo.class, VectorMetaInfo.Builder.class);
    }

    // Construct using com.vearch.grpc.entity.VectorMetaInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      dimension_ = 0;

      valueType_ = 0;

      storeType_ = 0;

      storeParam_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DataModel.internal_static_VectorMetaInfo_descriptor;
    }

    @Override
    public VectorMetaInfo getDefaultInstanceForType() {
      return VectorMetaInfo.getDefaultInstance();
    }

    @Override
    public VectorMetaInfo build() {
      VectorMetaInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public VectorMetaInfo buildPartial() {
      VectorMetaInfo result = new VectorMetaInfo(this);
      result.dimension_ = dimension_;
      result.valueType_ = valueType_;
      result.storeType_ = storeType_;
      result.storeParam_ = storeParam_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof VectorMetaInfo) {
        return mergeFrom((VectorMetaInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(VectorMetaInfo other) {
      if (other == VectorMetaInfo.getDefaultInstance()) return this;
      if (other.getDimension() != 0) {
        setDimension(other.getDimension());
      }
      if (other.valueType_ != 0) {
        setValueTypeValue(other.getValueTypeValue());
      }
      if (other.storeType_ != 0) {
        setStoreTypeValue(other.getStoreTypeValue());
      }
      if (!other.getStoreParam().isEmpty()) {
        storeParam_ = other.storeParam_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      VectorMetaInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (VectorMetaInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int dimension_ ;
    /**
     * <code>int32 dimension = 1;</code>
     * @return The dimension.
     */
    @Override
    public int getDimension() {
      return dimension_;
    }
    /**
     * <code>int32 dimension = 1;</code>
     * @param value The dimension to set.
     * @return This builder for chaining.
     */
    public Builder setDimension(int value) {

      dimension_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 dimension = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDimension() {

      dimension_ = 0;
      onChanged();
      return this;
    }

    private int valueType_ = 0;
    /**
     * <code>.VectorMetaInfo.ValueType value_type = 2;</code>
     * @return The enum numeric value on the wire for valueType.
     */
    @Override public int getValueTypeValue() {
      return valueType_;
    }
    /**
     * <code>.VectorMetaInfo.ValueType value_type = 2;</code>
     * @param value The enum numeric value on the wire for valueType to set.
     * @return This builder for chaining.
     */
    public Builder setValueTypeValue(int value) {

      valueType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.VectorMetaInfo.ValueType value_type = 2;</code>
     * @return The valueType.
     */
    @Override
    public VectorMetaInfo.ValueType getValueType() {
      @SuppressWarnings("deprecation")
      VectorMetaInfo.ValueType result = VectorMetaInfo.ValueType.valueOf(valueType_);
      return result == null ? VectorMetaInfo.ValueType.UNRECOGNIZED : result;
    }
    /**
     * <code>.VectorMetaInfo.ValueType value_type = 2;</code>
     * @param value The valueType to set.
     * @return This builder for chaining.
     */
    public Builder setValueType(VectorMetaInfo.ValueType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      valueType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.VectorMetaInfo.ValueType value_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValueType() {

      valueType_ = 0;
      onChanged();
      return this;
    }

    private int storeType_ = 0;
    /**
     * <code>.VectorMetaInfo.StoreType store_type = 3;</code>
     * @return The enum numeric value on the wire for storeType.
     */
    @Override public int getStoreTypeValue() {
      return storeType_;
    }
    /**
     * <code>.VectorMetaInfo.StoreType store_type = 3;</code>
     * @param value The enum numeric value on the wire for storeType to set.
     * @return This builder for chaining.
     */
    public Builder setStoreTypeValue(int value) {

      storeType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.VectorMetaInfo.StoreType store_type = 3;</code>
     * @return The storeType.
     */
    @Override
    public VectorMetaInfo.StoreType getStoreType() {
      @SuppressWarnings("deprecation")
      VectorMetaInfo.StoreType result = VectorMetaInfo.StoreType.valueOf(storeType_);
      return result == null ? VectorMetaInfo.StoreType.UNRECOGNIZED : result;
    }
    /**
     * <code>.VectorMetaInfo.StoreType store_type = 3;</code>
     * @param value The storeType to set.
     * @return This builder for chaining.
     */
    public Builder setStoreType(VectorMetaInfo.StoreType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      storeType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.VectorMetaInfo.StoreType store_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStoreType() {

      storeType_ = 0;
      onChanged();
      return this;
    }

    private Object storeParam_ = "";
    /**
     * <code>string store_param = 4;</code>
     * @return The storeParam.
     */
    public String getStoreParam() {
      Object ref = storeParam_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        storeParam_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string store_param = 4;</code>
     * @return The bytes for storeParam.
     */
    public com.google.protobuf.ByteString
        getStoreParamBytes() {
      Object ref = storeParam_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        storeParam_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string store_param = 4;</code>
     * @param value The storeParam to set.
     * @return This builder for chaining.
     */
    public Builder setStoreParam(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      storeParam_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string store_param = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStoreParam() {

      storeParam_ = getDefaultInstance().getStoreParam();
      onChanged();
      return this;
    }
    /**
     * <code>string store_param = 4;</code>
     * @param value The bytes for storeParam to set.
     * @return This builder for chaining.
     */
    public Builder setStoreParamBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      storeParam_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:VectorMetaInfo)
  }

  // @@protoc_insertion_point(class_scope:VectorMetaInfo)
  private static final VectorMetaInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new VectorMetaInfo();
  }

  public static VectorMetaInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VectorMetaInfo>
      PARSER = new com.google.protobuf.AbstractParser<VectorMetaInfo>() {
    @Override
    public VectorMetaInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VectorMetaInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VectorMetaInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<VectorMetaInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public VectorMetaInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

